### ISSUE TITLE
Npcap 0.999.1 install : failed to create npcap service

### ISSUE THREAD

**Issue by Chrisnet46** [nmap/npcap#102]
Hi!

I've spend several hours trying to find a solution.

The details shows :  
Npcap WFP callout driver has been successfully installed
Unknown error! 80070002
Npcap LWF driver has failed to be installed
Failed to create the npcap service for ...

Thank you for your help.

[DiagReport-20200506-103013.txt](https://github.com/nmap/nmap/files/4585728/DiagReport-20200506-103013.txt)
[install.log](https://github.com/nmap/nmap/files/4585729/install.log)

Christophe

**Comment by dmiller-nmap** [comment]
Thanks for this report. Please provide NPFInstall.log from the Npcap installation directory and the SetupAPI.dev.log file from `%SYSTEMROOT%\INF\` so we can better diagnose the problem.

**Comment by Chrisnet46** [comment]
Here they are.
[NPFInstall.log](https://github.com/nmap/npcap/files/4660865/NPFInstall.log)
[setupapi.dev.log](https://github.com/nmap/npcap/files/4660867/setupapi.dev.log)

**Comment by Chrisnet46** [comment]
Hi Daniel,

The issue was closed maybe I did push the wrong button. I've attached the log files you have requested, can you have a look..

Thank you for your help.

Chris

**Comment by Chrisnet46** [comment]
Ok it's working now. I have booted in safe mode, removed microsoft km-test loopback and WAN (network monitor) driver and then I could install npcap.

**Comment by everiknow** [comment]
running the exe as an admin solved my problem
