### ISSUE TITLE
NPCAP v0.9990 blocks vmware network stack after wakeup

### ISSUE THREAD

**Issue by zdm** [nmap/npcap#106]
After installing v0.9990 i found strange issue, that was gone, after I uninstalled npcap.

If I put computer to sleep and wakeup - local vmware network become disabled until I perform full reboot. Disabled means that all running workstation how no network access, don't see network adapters.

**Comment by zdm** [comment]
v09992 - still break vmware.

**Comment by zdm** [comment]
Guys, latest version that doesn't blocks vmware after wakeup is v0.9989.
How can I help to fix this problem?

**Comment by dmiller-nmap** [comment]
@zdm Thanks for the update. Does this mean you have tried Npcap 0.9997? What version of VMWare are you using? Is Npcap installed in a guest VM or on the hypervisor system?

**Comment by zdm** [comment]
Yes, of course, I trying each new version in hope,  that it will work. ;-)
VMWare workstation pro 15.5.6.
Npcap installed on hypervisor (latest windows 10).

**Comment by vanc** [comment]
The issue affected a lot of VMware users. 
https://communities.vmware.com/t5/VMware-Workstation-Pro/After-sleep-w10-host-can-not-ping-guests-vmware-workstation-pro/m-p/2822017/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufEtKU1QxNjgwRExKWDNBfDI4MjIwMTd8U1VCU0NSSVBUSU9OU3xoSw

**Comment by kong62** [comment]
Same problem

**Comment by vanc** [comment]
I can confirm the latest version 1.20 fixed the issue. After upgrade from v0.9989 which was the last known good one, I tried the normal reproduction steps (sleep, wake up), and the VM adapters are still reachable. No disable/enable workaround needed.

**Comment by zdm** [comment]
yes, 1.20 works for me

**Comment by dmiller-nmap** [comment]
Thanks everyone for confirming Npcap 1.20 fixes the issue. The issue was related to hardware packet filters being altered by Npcap and not restored when it closed. The commit that fixed the issue was 7ea7deba9bc2ad6345126aa255176eb2a0097ee1.
