### ISSUE TITLE
npcap Error 8007007e

### ISSUE THREAD

**Issue by ParediiiS** [nmap/npcap#108]
so, i have read all the other posts about this error, but i still dont know how to fix it, so if any1 can
 give a straight up answer i would aprecciate it!
![Capturar](https://user-images.githubusercontent.com/42809912/79296911-a1be6f00-7ed4-11ea-9704-e05b8e4c8845.PNG)
![Capturar2](https://user-images.githubusercontent.com/42809912/79297170-4b9dfb80-7ed5-11ea-8e53-7408fd1661ba.PNG)
If i try to unnistall it, this shows up:
![Capturar3](https://user-images.githubusercontent.com/42809912/79297189-58baea80-7ed5-11ea-8ea4-7b6746b8c79b.PNG)

**Comment by dmiller-nmap** [comment]
Thanks for this report. I am consolidating all instances of error 8007007e (ERROR_MOD_NOT_FOUND) at #135. Please check that issue for potential workarounds or fixes.
