### ISSUE TITLE
Wifi limited connectivity redux

### ISSUE THREAD

**Issue by kjkrum** [nmap/npcap#109]
It looks like nmap/nmap#373 / nmap/nmap#610 / nmap/nmap#724 are back in npcap 0.9989 on Windows 7. I installed npcap along with Wireshark with whatever the default options were. As reported before, everything works until reboot, then wifi has limited connectivity. Getting wifi back does not require uninstallation, just removing npcap from the adapter as shown. This fixes the problem immediately without rebooting.
![npcap](https://user-images.githubusercontent.com/1007080/79182372-7ef06580-7dc3-11ea-903c-edd81ce1d310.PNG)

**Comment by dmiller-nmap** [comment]
We believe the original issue here was resolved in Npcap 0.9991, so we are closing this issue. If it persists, @kjkrum may reopen this issue.

@Permission13, if your DNS capture problems are not resolved by Npcap 0.9994, please open a new issue with the relevant details.
