### ISSUE TITLE
Error 8007007e while installing npcap

### ISSUE THREAD

**Issue by teamango** [nmap/npcap#111]
I tried two versions: _0.9986_ and _0.9989_, but nothing worked. I also done all my pending updates on Windows 10. 
I need **Npcap** for **Wireshark**. I searched all over internet and I see that Winpcap could work too, but it didn't work either. 

I really don't know what to do anymore. 
![fdfdef](https://user-images.githubusercontent.com/33987689/77848833-3dab6380-71d0-11ea-9e57-203e1900ced4.PNG)

![gg](https://user-images.githubusercontent.com/33987689/77848837-4308ae00-71d0-11ea-82b9-99d4ca44b2e3.PNG)

**Comment by dmiller-nmap** [comment]
Thanks for this report. I am consolidating all instances of error 8007007e (ERROR_MOD_NOT_FOUND) at #135. Please check that issue for potential workarounds or fixes.
