### ISSUE TITLE
Npcap - no raw 802.11 packets captured on Win10

### ISSUE THREAD

**Issue by pr0mixe** [nmap/npcap#120]
Hello,
I've had this problem for a couple of months now, been waiting for newer versions of Npcap, but the lastest version 0.9986 still has the same issue:
Npcap works fine capturing _regular data packets_, but as soon as I switch to the Monitor Mode, either inside Wireshark or via wlanhelper.exe, there are no packets received by Wireshark, the capture window stays blank. Tried it on 3 (!) different Windows 10 machines (two x64, one x86), including a brand new clean Win10 install. Tried with two USB 802.11 interfaces that have been working fine on other machines. Tried all versions of Npcap between 0.991 and 0.9986 - nothing brings back the Monitor Mode packet capture... Tried Wireshark versions from 3.0.3 to 3.2.0. 
I thought that maybe starting with Win10 1903 something got broken because I haven't been able to see 802.11 packets on multiple installs of 1903, but the latest puzzle is one of the machines being 1803 and the same issue exists. But my other 1803 machine works just fine %%, been using Npcap 0.9981 & Wireshark 3.0.6 and with the same USB adapters as above I can see raw 802.11 packets as expected.
How do I diagnose this issue? Any logs to look into? 
To recap:
1) Npcap IS working when capturing regular data, not raw 802.11
2) Monitor Mode DOES get enabled, but no packets are received.
3) Same versions of Npcap/WS with same hardware and OS DO work on some other machines, but not universally on every machine..
Thanks!

**Comment by risinek** [comment]
I have the exact same issue. Was there any progress on this one?

**Comment by dmiller-nmap** [comment]
Raw WiFi frame capture was broken after Npcap 0.9983. This issue has been fixed in Npcap 1.30.
