### ISSUE TITLE
npcap-0.9984 failed to setup on Windows10

### ISSUE THREAD

**Issue by woshixiaobaissss** [nmap/npcap#123]
Hello,

I have some trouble installing ncap on win10...

Unknown error! 8007007 e
Npcap LWF driver (with Wi-Fi support) has failed to be installed.
Failed to create the npcap service for Win7, Win8 and Win10
![image](https://user-images.githubusercontent.com/41034819/68650429-f80f3680-055f-11ea-869f-2ef8f3f00311.png)
DiagReport.txt
[DiagReport-20191112-151511.txt](https://github.com/nmap/nmap/files/3834852/DiagReport-20191112-151511.txt)

**Comment by dmiller-nmap** [comment]
Thanks for this report. I am consolidating all instances of error 8007007e (ERROR_MOD_NOT_FOUND) at #135. Please check that issue for potential workarounds or fixes.
