### ISSUE TITLE
Npcap WLANHELPER unable to select channel with NETGEAR A6200

### ISSUE THREAD

**Issue by matthias-he** [nmap/npcap#132]
The below screenshot command sequence (in administrator mode) speaks for itself. WLANHELPER can set the Netgear A6200 into monitor mode but cannot set it to a specific WiFi channel or frequency. 

Npcpap was uninstalled and reinstalled with option "Support raw 802.11 traffic" checked, and the system was rebooted between uninstall and reinstall. No success. 

C:\Windows\System32\Npcap>netsh wlan show interfaces

There are 2 interfaces on the system:

    Name                   : Wi-Fi
    Description            : Realtek RTL8723BS Wireless LAN 802.11n SDIO Network Adapter
    GUID                   : 90236bb9-5db3-4cd6-8eeb-71feae3e559e
    Physical address       : 8c:18:d9:48:bd:89
    State                  : disconnected
    Radio status           : Hardware On
                             Software On

    Name                   : Wi-Fi 2
    Description            : NETGEAR A6200 WiFi Adapter
    GUID                   : f5e950fc-d049-4c10-938d-f59b05888be8
    Physical address       : 20:0c:c8:1e:71:4d
    State                  : disconnected
    Radio status           : Hardware On
                             Software On

    Hosted network status  : Not available

C:\Windows\System32\Npcap>wlanhelper f5e950fc-d049-4c10-938d-f59b05888be8 mode monitor
Success

C:\Windows\System32\Npcap>wlanhelper f5e950fc-d049-4c10-938d-f59b05888be8 channel 6
Error: makeOIDRequest::My_PacketOpenAdapter error (to use this function, you need to check the "Support raw 802.11 traffic" option when installing Npcap)
Failure

C:\Windows\System32\Npcap>wlanhelper f5e950fc-d049-4c10-938d-f59b05888be8 freq 2437
Error: makeOIDRequest::My_PacketOpenAdapter error (to use this function, you need to check the "Support raw 802.11 traffic" option when installing Npcap)
Failure

**Comment by gpotter2** [comment]
I'll bump this: npcap-0.9983 seems to have broken WlanHelper. Still applies in the latest versions

**Comment by Miaou** [comment]
Looks like 1.00 is still not working regarding this issue:

```
C:\Windows\System32\Npcap>wmic datafile where name="C:\\Windows\\System32\\drivers\\npcap.sys" get Version /value
Version=5.1.0.924

C:\Windows\System32\Npcap>WlanHelper.exe wifi modes
Error: makeOIDRequest::My_PacketOpenAdapter error (to use this function, you need to check the "Support raw 802.11 traffic" option when installing Npcap)
Failure
```

Now with 0.9982 (not even rebooted):
```
C:\Windows\System32\Npcap>wmic datafile where name="C:\\Windows\\System32\\drivers\\npcap.sys" get Version /value
Version=5.0.9982.730

C:\Windows\System32\Npcap>WlanHelper.exe wifi modes
master, managed, monitor
```
