### ISSUE TITLE
PCAP_OPENFLAG_NOCAPTURE_LOCAL not working on windows 10

### ISSUE THREAD

**Issue by graypacket** [nmap/npcap#137]
On Windows 10, even after setting the flag PCAP_OPENFLAG_NOCAPTURE_LOCAL, I'm still receiving packets indefinitely (packets sent by Adapter A are sent to Adapter B and vice versa, in a loop). I'm using the example code provided here https://github.com/nmap/npcap/tree/master/Examples/UserLevelBridge.

**Comment by dmiller-nmap** [comment]
Since we have not heard back, we will assume this issue has been fixed. If the same problem occurs with the current version of Npcap, you may reopen this issue and provide further details. Thanks!
