### ISSUE TITLE
SetInterface error, error code 50

### ISSUE THREAD

**Issue by ABVitali** [nmap/npcap#142]
[DiagReport-20190804-160810.txt](https://github.com/nmap/nmap/files/3464982/DiagReport-20190804-160810.txt)
I installed wireshark and Npcap but I couldn't select monitor mode in Wireshark.
Looking around for a solution I saw about the tool WlanHelper and when I try to use it from PowerShell I see "SetInterface error, error code = 50".
I couldn't find my WiFi card listed in the page https://secwiki.org/w/Npcap/WiFi_adapter so I decided to open this issue.

OS = Windows 10
Npcap version = 0.9982
Network interface name = Qualcomm Atheros Communications QCA9377
Network interface driver version = 12.0.0.720

Normal packets capturing with Wireshark works.

Let me know if you need other information. Thank you for your support.

**Comment by dmiller-nmap** [comment]
Error code 50 is ERROR_NOT_SUPPORTED. The adapter may not support monitor mode. Since raw WiFi capture was broken around the time this bug was reported, we suggest upgrading to Npcap 1.30 and trying again. Thanks!

**Comment by guyharris** [comment]
Presumably `pcap_can_set_rfmon()` will return 0 (as in "no, you can't set rfmon mode"), and `pcap_set_rfmon()` will return `PCAP_ERROR_RFMON_NOTSUP`, for adapters that don't support monitor mode.

**Comment by guyharris** [comment]
WlanHelper should perhaps check for `ERROR_NOT_SUPPORTED` and, rather than just printing "SetInterface error, error code = 50", report an error indicating that the problem may be that the driver (or adapter) may not support monitor mode.
