### ISSUE TITLE
When install the Npcap 0.992/0.994, it will show the error message.

### ISSUE THREAD

**Issue by ViktorYao** [nmap/npcap#147]
I install the Wireshark first, then it show the window about install Npcap 0.992.
When I install the Npcap 0.992, I got the error message about "Failed to create the npcap service for Win7, Win8, Win10. Please try installing Npcap again, or use the latest official Npcap installer from https://nmap.org/npcap/".
Actually, even I installed the latest version(v0.994), it still show the same error message.
Do you guys have any idea or suggestion?
Thanks a lot.

**Comment by dmiller-nmap** [comment]
These versions of Npcap are too far out of date to diagnose. Please try again with Npcap 0.9994. If you still have problems, open a new issue and include the `NPFInstall.log` file from the Npcap installation directory. Thanks!
