### ISSUE TITLE
Win 10 1809, Unknown error! 8000ffff; Npcap LWF driver has failed to be installed.

### ISSUE THREAD

**Issue by rugabunda** [nmap/npcap#157]
Unknown error! 8000ffff
Npcap LWF driver has failed to be installed.
Failed to create the npcap service for Win7, Win8 and Win10
Finish setting system restore point: Before installation of Npcap 0.99-r2

Same issue with 0.99-r8

Logs attached 
[Npcap.zip](https://github.com/nmap/nmap/files/2822493/Npcap.zip)

Not sure what is going on here; no antivirus running here.

**Comment by fyodor** [comment]
Thanks, everyone, for the good notes and discussion!  I'm closing this issue because the original poster (and some of the followup commenters) found resolution.  If anyone is still having problems related to this with Npcap version 0.9991 or newer, please file a new issue.  Cheers!
