### ISSUE TITLE
Cannot Set Device Frequency for Monitor Mode

### ISSUE THREAD

**Issue by ArnoAurelien** [nmap/npcap#159]
Hello,

I apologize for my noobie question but after looking hard for threads with the solution to my problem, I'm still stuck so...

I am running Windows 7 professional, I use a CISCO WUSB600n USB Wireless device my system recognizes and which functions properly when I use it to access the internet. My computer, a lenovo naturally has wifi, so I'd like to use that to connect to the internet as I usually do and use the CISCO WUSB600n in monitor mode, for testing purposes. I uninstalled Wincap and successfully installed npcap-0.99-r8.exe, and the command

WlanHelper "Wireless Network Connection 2" mode monitor

returns "success" and puts the CISCO WUSB600n in monitor mode while my native wifi interface accesses the internet. So far so good. I have a problem when using the command:

WlanHelper "Wireless Network Connection 2" channel 3

which I want because my 802.11n access point is set to channel 3, but I get 

Error: makeOIDRequest::My_PacketOpenAdapter error (to use this function, you need to check the "Support raw 802.11 traffic" option when installing Npcap)

even though I triple checked I did indeed check the "Support raw 802.11 traffic" option when installing Npcap.

...what could I do ? Can I send you some log files of my errors ? Where are they located ?

Thank you very much,
Arno.

**Comment by AndreKR** [comment]
Yes, this seems to be a regression? https://github.com/nmap/npcap/issues/132#issuecomment-646208410
