### ISSUE TITLE
can't get monitor mode to work (win10 1809, atheros Atheros AR9271)

### ISSUE THREAD

**Issue by fjleon1980** [nmap/npcap#160]
uninstalled winpcap, installed latest stable npcap, installed latest wireshark. Found a tip on the wifi adapters page to install the win8 driver listed there. 

I see the monitor mode checkbox but if i click it it doesn't stay checked.
Tried manually to set monitor mode with wlanhelper and it apparently worked.

However i start capturing and somehow the only packets i see from my iPad are mDNS packets, and very few of them. I can't see any other type of traffic.

Is this strictly a driver issue or is there something else i can do?

**Comment by dmiller-nmap** [comment]
The "self-unchecking monitor mode box" issue is caused by the `PacketSetMonitorMode()` function using an API that requires Administrator privileges. We changed this in Npcap 1.30, along with fixing lots of other WiFi-capture-related issues.
