### ISSUE TITLE
NCAP 0.99-r7 failed to setup on Windows10

### ISSUE THREAD

**Issue by YankeeThomsen** [nmap/npcap#162]
Hello,

I have some trouble installing ncap on win10...

Unknown error! 80071a46
Npcap LWF driver (with Wi-Fi support) has failed to be installed.
Failed to create the npcap service for Win7, Win8 and Win10

![unbenannt](https://user-images.githubusercontent.com/42940470/44992706-5756db80-af98-11e8-8610-6f6be6581590.PNG)

C:\Windows\INF\setupapi.dev.log

...
>>>  [Install network driver - INSECURE_NPF]
>>>  Section start 2018/09/03 16:18:55.338
      cmd: "C:\Program Files\Npcap\NPFInstall2.exe" -n -i2
     dvi: Installing new driver
     dvi: {Create Device} 16:18:55.392
     dvi:      {Create Device - INSECURE_NPF}
     dvi:           Class GUID  - {4d36e974-e325-11ce-bfc1-08002be10318}
     dvi:           Description - <none>
     dvi:           Flags       - 0x00000001
     dvi:           Created device 'ROOT\INSECURE_NPF\0000'
     dvi:      {Create Device - exit(0x00000000)}
     dvi: {Create Device - exit(0x00000000)} 16:18:55.521
     dvi: {Build Driver List} 16:18:55.539
     dvi:      Searching for hardware ID(s):
     dvi:           insecure_npf
     dvi:      Created Driver Node:
     dvi:           HardwareID   - INSECURE_NPF
     dvi:           InfName      - C:\WINDOWS\System32\DriverStore\FileRepository\npf.inf_amd64_66\npf.inf
     dvi:           DevDesc      - Npcap Packet Driver (NPF)
     dvi:           Section      - FilterStandard
     dvi:           Rank         - 0x00ff0000
     dvi:           Signer Score - WHQL
     dvi:           DrvDate      - 07/05/2018
     dvi:           Version      - 17.11.39.715
     dvi: {Build Driver List - exit(0x00000000)} 16:18:55.953
     dvi: {Select Best Driver}
     dvi:      Class GUID of device changed to: {4d36e974-e325-11ce-bfc1-08002be10318}.
     dvi:      Selected Driver:
     dvi:           Description - Npcap Packet Driver (NPF)
     dvi:           InfFile     - c:\windows\system32\driverstore\filerepository\npf.inf_amd64_66\npf.inf
     dvi:           Section     - FilterStandard
     dvi: {Select Best Driver - exit(0x00000000)}
     dvi: Selected driver:
     dvi:      INF path C:\WINDOWS\INF\oem14.inf
     dvi:      INF section FilterStandard
     dvi:      INF version 17.11.39.715
     sig: {_VERIFY_FILE_SIGNATURE} 16:18:56.174
     sig:      Key      = npf.sys
     sig:      FilePath = C:\WINDOWS\system32\DRIVERS\npf.sys
     sig:      Catalog  = C:\WINDOWS\System32\DriverStore\FileRepository\npf.inf_amd64_66\npf.cat
     sig:      Success: File is signed in catalog.
     sig: {_VERIFY_FILE_SIGNATURE exit(0x00000000)} 16:18:56.523
     flq: File 'C:\WINDOWS\system32\DRIVERS\npf.sys' pruned from copy.
     inf: {Install from INF Section - FilterStandard} 16:18:56.559
     inf:      Flags         - 0x000007af
     inf: {Install from INF Section - exit(0x00000000)} 16:18:56.600
     inf: Flags: 0x00000000
     inf: AddService=npf,,FilterStandard.svc  (oem14.inf line 158)
     dvi: Add Service: Created service 'npf'.
     inf: {Install from INF Section - FilterStandard.svc} 16:18:56.678
     inf:      Flags         - 0x00100004
     inf: {Install from INF Section - exit(0x00000000)} 16:18:56.715
     inf: {Install from INF Section - FilterStandard} 16:18:56.738
     inf:      Flags         - 0x00000040
     inf: {Install from INF Section - exit(0x00000000)} 16:18:56.774
     dvi: Committing changes to the network graph
<<<  Section end 2018/09/03 16:19:04.774
<<<  [Exit status: SUCCESS]

do you have any suggestions how to solve this?

Thank you! & Best greets!

**Comment by fyodor** [comment]
Thanks for the report.  I'm closing this now because both Npcap and Windows 10 have changed substantially since 2018.  If anyone is still having this issue with Npcap 0.9991 or later, please comment here with details and I'll re-open.

**Comment by AZSOC** [comment]
This is happening on a Windows 10 machine today from one of my students.
![npcap error](https://user-images.githubusercontent.com/63419964/83088486-b13ee500-a048-11ea-80a0-bb38dcab8457.png)

**Comment by shllshckd** [comment]
Npcap OEM 0.9982 setup
Failed to create the npcap service for Win7, Win8 and Win10.
Other than that line, it's the same error message as the one @AZSOC provided.
I'm running Windows 10 x64

**Comment by dcui** [comment]
I got the same error reported by AZSOC when trying to install npcap-0.9995.exe on a Windows Server  Version 1803 (OS Build 17134.1) -- I ran "winver.exe" to get the version info.

**Comment by mduCantoo** [comment]
I am having this error now. First with WireShark installation and then with the newest installer. I searched the registry for the key mentioned by Rugabunda but that path doesn't exist in my registry. What else could be stopping this from installing?

[install.log](https://github.com/nmap/npcap/files/5065653/install.log)
[NPFInstall.log](https://github.com/nmap/npcap/files/5065655/NPFInstall.log)
![npcap install error message](https://user-images.githubusercontent.com/24396282/90066868-2b275780-dca3-11ea-8d2a-7ccf3d3604cf.png)

**Comment by dcui** [comment]
https://github.com/nmap/nmap/issues/1511 says:

JeremyHH commented on Oct 30, 2019
In fact I've succeeded to install it after having disabled drivers signature enforcement (https://windowsreport.com/driver-signature-enforcement-windows-10/), so I can close that ticket

Can someone here try the same thing?  @mduCantoo.
I'll try it later this week when I have a chance.

**Comment by mduCantoo** [comment]
> [nmap/nmap#1511](https://github.com/nmap/nmap/issues/1511) says:
> 
> JeremyHH commented on Oct 30, 2019
> In fact I've succeeded to install it after having disabled drivers signature enforcement (https://windowsreport.com/driver-signature-enforcement-windows-10/), so I can close that ticket
> 
> Can someone here try the same thing? @mduCantoo.
> I'll try it later this week when I have a chance.

That isn't something I am going to be able to do. I will have to put in a ticket with our support team or see if my supervisor has authority to do that.

Thank you for the link to the article. I will pass that along.

**Comment by dmiller-nmap** [comment]
This is a closed issue for a very old version of Npcap. If any of you are still having installation problems, please try again with Npcap 0.9997 and search the *open* issues for the error number that is displayed. If there is no matching *open* issue, please open a new issue and include the error number. Example search for the error in this issue: https://github.com/nmap/npcap/issues?q=is%3Aissue+is%3Aopen+80071a46
