### ISSUE TITLE
Npcap OEM 0.9991: Install failure still leaves npcap files behind

### ISSUE THREAD

**Issue by akontsevoy** [nmap/npcap#170]
nmap/nmap#2013 is still not fixed as of 0.9991. Failure to install Npcap driver, for example, still leaves Npcap installation directory with all files (and more seriously, `%SystemRoot%\System32\Npcap\wpcap.dll`) behind. This has already been reported as fixed twice (in nmap/nmap#1910 and in nmap/nmap#2013), yet still not properly fixed.

**Comment by dmiller-nmap** [comment]
Npcap 0.9993 installer will run its own uninstaller if anything fails after the previous version is uninstalled. This means that a failure in the previous version's uninstaller will not cause the new uninstaller to run, hopefully preserving an existing installation. But any other install failure will leave only the installer logs in the installation directory; no DLLs or drivers will be left on the system.
