### ISSUE TITLE
pcap_next_ex returns 0

### ISSUE THREAD

**Issue by pfliu721** [nmap/npcap#176]
Wireshark can see that there are packets on the interface, but pcap_next_ex returns 0. Sometimes  pcap_next_ex returns packets of normal length, but only a few dozen packets, and then keep returning 0. Sometimes it returns a very large value and then it doesn't respond, or it doesn't return any packets at all.
Can you give me some advice? Thank you very much。

**Comment by dmiller-nmap** [comment]
This is due to a bug in Npcap 0.9991, which is solved in the latest release. Please update to Npcap 0.9993.
