### ISSUE TITLE
Npmap Is so broken and fixes?

### ISSUE THREAD

**Issue by LOOF-sys** [nmap/npcap#179]
Ok so anyone got any fixes to this it says at the bottom v v v
 "Stopping the npcap driver
Output folder: C:\Program Files\Npcap
Extract: LICENSE
Extract: DiagReport.bat
Extract: DiagReport.ps1
Extract: FixInstall.bat
Extract: NPFInstall.exe
Output folder: C:\Program Files\Npcap
Extract: npcap.sys
Extract: npcap.cat
Extract: npcap.inf
Extract: npcap_wfp.inf
Output folder: C:\Program Files\Npcap
Extract: Uninstall.exe
Installing NDIS6.x x64 driver for Win7, Win8 and Win10
Output folder: C:\WINDOWS\system32
Extract: wpcap.dll
Extract: Packet.dll
Extract: NpcapHelper.exe
Extract: WlanHelper.exe
Output folder: C:\WINDOWS\system32\Npcap
Extract: wpcap.dll
Extract: Packet.dll
Extract: NpcapHelper.exe
Extract: WlanHelper.exe
Output folder: C:\WINDOWS\system32
Extract: wpcap.dll
Extract: Packet.dll
Extract: NpcapHelper.exe
Extract: WlanHelper.exe
Output folder: C:\WINDOWS\system32\Npcap
Extract: wpcap.dll
Extract: Packet.dll
Extract: NpcapHelper.exe
Extract: WlanHelper.exe
Npcap driver cache in Driver Store has been successfully cleaned up!
The cache in driver store was cleared
Npcap WFP callout driver has been successfully installed!
Unknown error! 8007007e
Npcap LWF driver (with Wi-Fi support) has failed to be installed.
Failed to create the npcap service for Win7, Win8 and Win10 "
Any fixes??? any program with Npcap has this saome error it always says Failed to create Win7, Win8, Win10. please give me some advice :/

**Comment by fyodor** [comment]
I'm closing this one because it doesn't really give us enough information to go on.  You might want to try Npcap 0.9994, which is the newest version now.
