### ISSUE TITLE
Npcap 0.9992 installer warning

### ISSUE THREAD

**Issue by vient** [nmap/npcap#182]
The installer shows that npcap is currently in use by program `.`. If you choose Ignore or Retry, installation will successfully continue.  Since `.` is a pretty weird name for a program and it reproduces each time, I suspect it might be a bug.

**Comment by guyharris** [comment]
I saw that as well.

It showed up when I tried installing 0.9992 on a system with 0.9991 installed, *and* on the same system after I'd uninstalled 0.9992 (so I could do a simple reinstall), rebooted (to make sure no program was hanging around), and reinstalled.

I suspect the "." is supposed to be the period at the end of a sentence, and there was supposed to be a list of programs there, i.e. the list is empty.

(Is this from code inside NSIS?)

**Comment by vient** [comment]
I tried to do it your way (uninstall, reboot, install + reboot), it did not help.

At least I know now that even "Abort" option does not, in fact, abort. All three of them do nothing and continue with installation successfully.

I'm testing loopback with running `ping localhost`, usually it works.

**Comment by dmiller-nmap** [comment]
This shows up only when the installer tries to remove WinPcap. We try to check for processes using the DLLs by running `NPFInstall.exe -check_dll`, but we had not yet unpacked the NPFInstall.exe tool. Npcap 0.9993 resolves this problem, along with several other stability fixes.
