### ISSUE TITLE
Update Npcap Users Guide to note winpcap_mode changes 

### ISSUE THREAD

**Issue by fyodor** [nmap/npcap#188]
We should update the /winpcap_mode option description to reflect our recent changes.  In particular, the default value is now yes.  That might actually be the only change needed. Then we need to regenerate and post.

**Comment by dmiller-nmap** [comment]
This is done in the source. I'll check on why it isn't on the website yet.

**Comment by dmiller-nmap** [comment]
Done. Updating the website requires several local checkouts to be up-to-date to ensure the final output is current, and the Npcap source checkout was out of date last time.
