### ISSUE TITLE
Wireshark crahses my PC when I stop the recording

### ISSUE THREAD

**Issue by vnick001** [nmap/npcap#191]
As requested by Guy Harris, I forward the Wireshark bug report (https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=16634) here after having reinstalled Wireshark 3.2.4 but with the latest NPcap 0.9994 as he recommended.
The PC crashes reported there happened 3 times this morning already after an even shorter recording period (< 20 min) with very few UDP frames.

It currently looks as if this problem has something to do with the DigiView (Logic Analyzer) tool I use (for observing my SPI bus  - I develop an SPI to UDP converter).
(See https://www.tech-tools.com/DV518-logic-analyzer.htm) because if I do not use it in parallel with Wireshark, Wireshark does not seem to crash my PC any more (so far).
This is my SW version of it if you want to try and reproduce the failure:
https://www.tech-tools.com/files/digiview-930.exe
It should run without the HW tool.

I have attached a typical Wireshark test recording I managed to save before a crash for a better impression on what is recorded (although I do not think this really has something to do with the problem).

Let me know if I can do anything more to help resolving this!

/Typical_Wireshark_SPI2UDP_2_data_channels_with_2_Adafruits_32bit-mode_10MHz_short_delay_in_between.pcapng.zip)

**Comment by dmiller-nmap** [comment]
Thanks for this report. The most useful information to debug this would be the kernel minidump file from `C:\Windows\Minidump\`. Since this may include sensitive information, you may send it privately to dmiller@nmap.com instead of attaching it here. We will also try to reproduce the issue here.

**Comment by dmiller-nmap** [comment]
I received the crash dumps, thank you. Npcap is not shown in the stack trace of the crash. Instead, a driver for a D-Link USB 3.0 to Gigabit Ethernet adapter seems to be the cause of the crash. The timestamp on the driver is from 2016, and there appears to be an updated version from 2018 available [from D-Link](https://support.dlink.com/ProductInfo.aspx?m=DUB-1312). I would suggest upgrading this driver and seeing if it resolves your problems. If not, you should probably file a support request with D-Link to get the issue resolved.

Debugger output:

```
BugCheck 1000007E, {ffffffffc0000005, fffff806843045bc, ffffc105d8d0f1c8, ffffc105d8d0ea10}

*** WARNING: Unable to verify timestamp for DUB-13X2.sys
*** ERROR: Module load completed but symbols could not be loaded for DUB-13X2.sys
*** WARNING: Unable to verify timestamp for win32k.sys
*** ERROR: Module load completed but symbols could not be loaded for win32k.sys
Probably caused by : DUB-13X2.sys ( DUB_13X2+2c76 )

Followup:     MachineOwner
---------

6: kd> kn
 # Child-SP          RetAddr           Call Site
00 ffffc105`d8d0e1a8 fffff806`80bdb6b6 nt!KeBugCheckEx
01 ffffc105`d8d0e1b0 fffff806`80b9d389 nt!PspSystemThreadStartup$filt$0+0x44
02 ffffc105`d8d0e1f0 fffff806`80bcb18f nt!_C_specific_handler+0xa9
03 ffffc105`d8d0e260 fffff806`80a89855 nt!RtlpExecuteHandlerForException+0xf
04 ffffc105`d8d0e290 fffff806`80a8ddee nt!RtlDispatchException+0x4a5
05 ffffc105`d8d0e9e0 fffff806`80bd431d nt!KiDispatchException+0x16e
06 ffffc105`d8d0f090 fffff806`80bd0503 nt!KiExceptionDispatch+0x11d
07 ffffc105`d8d0f270 fffff806`843045bc nt!KiPageFault+0x443
08 ffffc105`d8d0f400 fffff806`84364e5d Wdf01000!FxPoolFree+0x20 [minkernel\wdf\framework\shared\object\wdfpool.cpp @ 431] 
09 (Inline Function) --------`-------- Wdf01000!FxStump::operator delete+0x5 [minkernel\wdf\framework\shared\inc\private\common\fxstump.hpp @ 55] 
0a ffffc105`d8d0f440 fffff806`843682da Wdf01000!FxInternalIoctlOthersContext::`scalar deleting destructor'+0x1d
0b ffffc105`d8d0f470 fffff806`8431f404 Wdf01000!FxRequestBase::SetContext+0x32 [minkernel\wdf\framework\shared\inc\private\common\fxrequestbase.hpp @ 258] 
0c ffffc105`d8d0f4a0 fffff806`8436c597 Wdf01000!FxSyncRequest::FxSyncRequest+0x11608 [minkernel\wdf\framework\shared\core\fxsyncrequest.cpp @ 95] 
0d ffffc105`d8d0f4f0 fffff806`a0992c76 Wdf01000!imp_WdfUsbTargetDeviceSendUrbSynchronously+0x97 [minkernel\wdf\framework\shared\targets\usb\km\fxusbdeviceapikm.cpp @ 103] 
0e ffffc105`d8d0f770 ffffc80b`e62241a0 DUB_13X2+0x2c76
0f ffffc105`d8d0f778 fffff806`85aec622 0xffffc80b`e62241a0
10 ffffc105`d8d0f780 fffff806`a0998742 ndis!NdisCancelTimerObject+0x82
11 ffffc105`d8d0f7d0 ffffc105`db597930 DUB_13X2+0x8742
12 ffffc105`d8d0f7d8 ffffc105`db597930 0xffffc105`db597930
13 ffffc105`d8d0f7e0 ffffc105`d8d0f899 0xffffc105`db597930
14 ffffc105`d8d0f7e8 00000000`00000010 0xffffc105`d8d0f899
15 ffffc105`d8d0f7f0 ffffc80b`e60fc170 0x10
16 ffffc105`d8d0f7f8 00000000`00000000 0xffffc80b`e60fc170
6: kd> lmDvmDUB_13X2
Browse full module list
start             end                 module name
fffff806`a0990000 fffff806`a09a9000   DUB_13X2 T (no symbols)           
    Loaded symbol image file: DUB-13X2.sys
    Image path: \SystemRoot\System32\drivers\DUB-13X2.sys
    Image name: DUB-13X2.sys
    Browse all global symbols  functions  data
    Timestamp:        Mon Jul  4 16:34:56 2016 (577AD680)
    CheckSum:         0001B562
    ImageSize:        00019000
    Translations:     0000.04b0 0000.04e4 0409.04b0 0409.04e4
    Information from resource tables:
```
