### ISSUE TITLE
NPCAP lowering 10gb network adapter throughput to under 2gb

### ISSUE THREAD

**Issue by jgmoras** [nmap/npcap#195]
I am an OEM customer for NMAP/NPCAP. One of my customers has reported that they were seeing the NPCAP driver on WIndows servers lower the throughput considerably.

Testing  shows  with NPcap is installed and filter driver loaded, a 10Gb virtual network adapter VMXNET3 interface inbound bandwidth is limited to a little over 1Gb-2Gb.  This also results in increase count of Rx Discards on the server port since the traffic is filling the buffer and it not being processed fast enough, therefore the packets are dropped.

We have performed testing with 
·       Npcap installed/loaded: versions tested:  9982, 9984, and 9994
·       VMXNET3 Driver:  1.8.16.0
·       Windows Server (2016 tested)

Disabling the kernel driver for npcap resolves the throughput issue
SERVICE_NAME: npcap
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1077  (0x435)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

This driver is in more recent vmware tools - we areu using  VMware Tools 11.1.1 with Hardware Drivers vmxnet3 | 1.8.16.0

NPCAP enabled shows ethernet throughput at 1.6Gbps while running tests
![image](https://user-images.githubusercontent.com/13950597/85451876-51186180-b568-11ea-8879-ddb066039309.png)

And after disabling the NPCAP driver throughput at 8.9Gbps
![image](https://user-images.githubusercontent.com/13950597/85452016-7311e400-b568-11ea-812f-717dd3cb2e9f.png)

I have done some other research and I am guessing this is a known limitation but I am wondering if this is documented somewhere that I have not found? I see wireshark notes that there are issues on 10Gb adapters and reducing bandwith is necessary to keep up - the use we have is strictly capturing NMAP data so I am wondering if there is a configuration that can be used to allow use w/o reducing bandwidth? If not is there any plan for a fix or a doc listing this limitation.

Thanks!

**Comment by dmiller-nmap** [comment]
This is due to Npcap being a NDIS 6.20 filter driver. RSC support was added in NDIS 6.30, and is necessary for such high throughput. We are working on differentiated builds for Windows 10 (NDIS 6.50) vs earlier Windows versions (NDIS 6.20, the highest supported by Windows 7). See #70

**Comment by dmiller-nmap** [comment]
Npcap 0.9995 should address this issue on Windows 10-based systems including Server 2016 and Server 2019. Feel free to update with your confirmation or test results, or let us know if the issue persists. If you need RSC capability on Windows 8 or 8.1, please open a new issue.
