### ISSUE TITLE
Upgrade Npcap build to use newer Visual Studio

### ISSUE THREAD

**Issue by fyodor** [nmap/npcap#197]
Right now we are building our Npcap packages using Visual Studio 2015.  But for future enhancements, we may require newer versions.  For example, ARM64 support apparently requires VS 2017 or later (issue #57 ).  And there may be other important improvements in later compilers which enhance efficiency and/or security and perhaps even add useful features.

**Comment by lucloner** [comment]
it could open and compile with vs 2019 if you got right envirment. but could not compile with arm/arm64 profile, i guess i would manage some header files and implememts... i m not finished yet.
and!!! you can not install not signed npcap driver!!! 
Enable testsigning (bcdedit /set testsigning on)
you really want to do this?

**Comment by dmiller-nmap** [comment]
Npcap 0.9996 and later were built with VS2019 and WDK 10.0.18362.0.

**Comment by guyharris** [comment]
Have the build files (.sln, .vcxproj) been updated?  Is that a requirement for adding ARM64 support, as per pull request #18?

**Comment by dmiller-nmap** [comment]
@guyharris Yes, that part was done in 665ae79371e8fdad5a880a147341ade1edf06608

**Comment by guyharris** [comment]
OK, so, at this point, I'd say @pmsjt  should close #18, take the tip of the master Npcap branch, and create a new pull request based on that.
