### ISSUE TITLE
Upgrade npcap.sys to NDIS 6.50

### ISSUE THREAD

**Issue by fyodor** [nmap/npcap#198]
We need to upgrade the Npcap driver (npcap.sys) to NDIS 6.50 (from 6.20) to take advantage of new features like Receive Side Coalescing (RSC - See issue #70 ).  Since Windows 10 is required to support NDIS 6.50, we also need to implement the split-driver approach (Issue #196 ) so we build and still install an NDIS 6.20 driver on pre-Win10 systems.

**Comment by guyharris** [comment]
Is this now fixed?  [The Npcap CHANGELOG](https://github.com/nmap/npcap/blob/master/CHANGELOG.md) says

* On Windows 10, the Npcap driver has been updated to NDIS 6.50 and Windows 10 WFP compatibility, supporting network stack improvements like RSC. Fixes #196.

**Comment by dmiller-nmap** [comment]
Npcap 0.9995 installs a NDIS 6.50 driver on Windows 10-based systems including Server 2016 and Server 2019
