### ISSUE TITLE
Connectivity problems related to Npcap Loopback Adapter

### ISSUE THREAD

**Issue by mwpowellhtx** [nmap/npcap#199]
I upgraded to Windows 10 Pro recently, updated to creators build v2004, am on a wired network connection. Was working fine under win7, but since win10, was showing "no internet" with "limited" connectivity.

I was connected, but if any apps probe the Ethernet, would reject since it was signaling "no internet". Well, that went on for a couple of weeks until finally last evening my network stacks completely failed. Even my Wi-Fi adpater would not connect after awhile.

I did some digging and isolated it to the `Npcap Loopback Adapter`, ran the litany of `netsh` resets, disabled the device in the device manager, and lo and behold, Ethernet functioning now, Ethernet connected system tray icon back.

**Comment by fyodor** [comment]
Thanks for your report.  Do you know what version of Npcap you had installed?  Would you try installing version 0.9994 and report back how it goes?  I'm updating the title of this issue to something more descriptive.

**Comment by mwpowellhtx** [comment]
@fyodor I can look into it. How would I find that out? I look in the properties of the device, but it reports `Microsoft 10.0.19041.1`.

Just to clarify, I do not pick up `Npcap Loopback Adapter` apart from `Wireshark`, correct? Or does it come "naturally" in the Win 10 Pro support?

**Comment by mwpowellhtx** [comment]
@fyodor Okay, in the installed programs, Npcap reporting `0.9991`.

**Comment by dmiller-nmap** [comment]
@mwpowellhtx Thanks for the report. Npcap 0.9991 has some significant performance regression, so we recommend upgrading to Npcap 0.9994.

The Npcap Loopback Adapter is installed by Npcap as part of the "Legacy loopback support" option. Most software will not need this installed, and it does sometimes interfere with network connectivity when other software like VPN or endpoint security software is installed. We recommend removing it (reinstall and un-check the "Legacy loopback support" option) unless you know you need it for e.g. Nmap scanning of localhost. Wireshark can capture loopback traffic without it.

**Comment by mwpowellhtx** [comment]
Also, I wonder, I also read some blurbs about this issue interfering with the Sound via the system tray, does not respond to left or right mouse clicks. I've got that symptom as well. I can get to Sound via the start menu "Sound" alternatively.

@dmiller-nmap Yeah, no worries. I should be able to do that with or without `Wireshark` upgrading?

**Comment by guyharris** [comment]
> @dmiller-nmap Yeah, no worries. I should be able to do that with or without `Wireshark` upgrading?

You can run a new Npcap installer to upgrade Npcap without needing to update Wireshark.

**Comment by mwpowellhtx** [comment]
Appreciate that. Worst case, if that does not work, or breaks down again, I'll reinstall Wireshark.

**Comment by guyharris** [comment]
> Appreciate that. Worst case, if that does not work, or breaks down again, I'll reinstall Wireshark.

The next 3.2.x release (3.2.5) is currently scheduled for 2020-07-01, and will probably ship with 0.9994 (unless an 0.9995 comes out *really* soon), so if you can wait until 3.2.5 comes out before reinstalling Wireshark, you can get Npcap 0.9994 "for free".

**Comment by mwpowellhtx** [comment]
Machine booted up this morning, `Ethernet` failed to come up healthy even with `Npcap` disabled, indicating "No Internet." Tried installing the latest `Npcap` to no avail. I'm rebooting, first to install a second network card, second just to see if it comes up healthy an reporting "Connected."

@guyharris Any clue as to when that update might be rolling out?

Thanks.

**Comment by guyharris** [comment]
> Machine booted up this morning, `Ethernet` failed to come up healthy even with `Npcap` disabled, indicating "No Internet." Tried installing the latest `Npcap` to no avail. I'm rebooting, first to install a second network card, second just to see if it comes up healthy an reporting "Connected."
> 
> @guyharris Any clue as to when that update might be rolling out?

If you mean the *Wireshark* update, it will probably come out today today - ***BUT***, if Npcap 0.9994 is still causing connectivity problems, the chances that the Wireshark update will make any difference are somewhere between slim and none, given that it will install...

...Npcap 0.9994.

I have no idea when the next Npcap update will come out, and have no idea whether it'll fix your problem, as I don't know what's causing your problem.

**Comment by mwpowellhtx** [comment]
@guyharris Are there any logs I can review, offer, etc, to help shed some light on whatever is happening? Short of uninstalling `Npcap` altogether. However, reading about `Nmap`, that seems like something that might be a useful thing to know about from time to time.

**Comment by guyharris** [comment]
> @guyharris Are there any logs I can review, offer, etc, to help shed some light on whatever is happening?

@dmiller-nmap any suggestions for him?

> Short of uninstalling `Npcap` altogether. However, reading about `Nmap`, that seems like something that might be a useful thing to know about from time to time.

If you uninstall Npcap, you will either have to re-install it or install WinPcap if you want to capture network traffic with Wireshark.  I think Nmap also uses *pcap to inject and receive network traffic, so I think the same applies to Nmap.

**Comment by mwpowellhtx** [comment]
@guyharris Well, as far as the obvious symptoms, responses, expectations go, I completely understand. Having done a bit of digging, I would be very surprised that I was the only one experiencing this issue. However as Venn diagrams go, I should think the intersections of *Windows 10 Pro v2004 build 19041*, *Wireshark*, and/or *Npcap*, are pretty small.

Let me know if I can provide any further logs, etc, along these lines, to help shed some light on the matter vis-a-vis, apparently `Npcap` influenced "no internet" issues.

**Comment by mwpowellhtx** [comment]
For giggles, I just threw on an Intel based 2-port Ethernet PCIe card today, connecting over that at the moment, instead of my ASUS motherboard Realtek based. No difference, same result, Ethernet reporting "no internet". The odd thing is, for the past couple of days, I actually got a positive "connected", even under the "old" `Npcap` version. Just all of a sudden now saying "no internet". Pings still work, etc. Very odd.

**Comment by guyharris** [comment]
> @guyharris Well, as far as the obvious symptoms, responses, expectations go, I completely understand. Having done a bit of digging, I would be very surprised that I was the only one experiencing this issue. However as Venn diagrams go, I should think the intersections of _Windows 10 Pro v2004 build 19041_, _Wireshark_, and/or _Npcap_, are pretty small.

Again, Wireshark's primary involvement here is that it installs Npcap.  It does not, itself, directly interact with network devices when capturing, on *any* platform - it goes through libpcap/WInPcap/Npcap.

So this is best investigated as an Npcap issue; changing Wireshark is unlikely to affect it unless changing Wireshark also changes the Npcap version installed.

> Let me know if I can provide any further logs, etc, along these lines, to help shed some light on the matter vis-a-vis, apparently `Npcap` influenced "no internet" issues.

I'm not an Npcap developer (I'm a *libpcap* core developer, but that's not the part of Npcap that plugs into the Windows networking stack); Daniel Miller, @dmiller-nmap, is, so he's the one who would know what logs Npcap writes and that would be useful.
