### ISSUE TITLE
Guaranteed BSOD if disable interface whilst dumping in Windows 10

### ISSUE THREAD

**Issue by Nicholas-Johnson-opensource** [nmap/npcap#202]
If using Wireshark on Windows 10 (my computer uses v2004 build 19041.329), you get a guaranteed BSOD if you do any of the following:

1. Disable the interface from which you are dumping
2. Unload Internet Protocol Version 4 (TCP/IPv6) in adapter properties for the interface from which you are dumping
3. Unload Internet Protocol Version 6 (TCP/IPv6) in adapter properties for the interface from which you are dumping

I can provide more information at request.

**Comment by dmiller-nmap** [comment]
Thanks for this report. This is the same crash as #194, and is fixed in Npcap 0.9995.

**Comment by Nicholas-Johnson-opensource** [comment]
I fear the npcap installer / uninstaller is broken. No matter how many times I uninstall npcap on my computer, reboot and install 0.9995, it will not stop doing BSoD when disabling the interface. However, if I install 0.9995 on another computer which has not had Wireshark or npcap installed before, the issue does not happen. Does the uninstaller actually wipe the old npcap version from the computer? Or does this point to a deeper problem with my computer?

I do not know how closely you work with Wireshark but the Wireshark package I downloaded is still shipping npcap 0.9994 which could be considered to be carrying a denial of service vulnerability. It needs to be bumped to 0.9995. If you do not work with Wireshark then I can contact them and let them know.

Thanks!

**Comment by Nicholas-Johnson-opensource** [comment]
Using "sc stop npcap", then using "psexec.exe -s -i cmd" to become "nt authority\system" and deleting anything in "C:\Windows\System32" containing "npcap" in the filename, uninstalling, rebooting, installing 0.9995 and then rebooting, seems to have fixed it. Thanks.
