### ISSUE TITLE
Remove DAG support from packet32.dll

### ISSUE THREAD

**Issue by guyharris** [nmap/npcap#203]
Currently, libpcap has its own code to support DAG cards; I spoke to people from Endace, and they think that should work on Windows as well.

There's also code to support DAG cards in the packet32.dll source; it was added before libpcap had the notion of add-on modules.  It can probably be removed now; see the code that's ifdefed with `HAVE_DAG_API` and the defines `INFO_FLAG_DAG_CARD` and  `INFO_FLAG_DAG_FILE`.

**Comment by dmiller-nmap** [comment]
I like the idea of slimming down Packet32. Is there any SDK needed to build libpcap's DAG support? It might be nice to add that to Npcap.

**Comment by guyharris** [comment]
You might also want to get rid of `INFO_FLAG_DAG_CARD` and `INFO_FLAG_DAG_FILE` in `Common\Packet32.h` and fix the `TRACE_PRINT()` call in `PacketAddAdapterAirpcap()` to say `"PacketAddAdapterAirpcap: GlobalAlloc Failed"` instead of `"PacketAddAdapterDag: GlobalAlloc Failed"`.

**Comment by dmiller-nmap** [comment]
Definitely the TRACE_PRINT needs to change, but I think keeping those INFO_FLAG constants around is ok, even if they're unused, to avoid reusing those integers for future flags that might break compatibility with things built with the old Packet32.h.
