### ISSUE TITLE
发现两个断言。

### ISSUE THREAD

**Issue by kouzhudong** [nmap/npcap#207]
*** Assertion failed: pFiltMod->AdapterBindingStatus == FilterPaused
***   Source File: F:\git\network\nmap\npcap\packetWin7\npf\npf\Openclos.c, line 2631

Break repeatedly, break Once, Ignore, terminate Process, or terminate Thread (boipt)? i
i
这个是在卸载驱动的时候出现的。

还有一个是：
Openclos.c, line 2562的：ASSERT(pFiltMod->AdapterBindingStatus == FilterPaused);
这个是在操作系统启动的时候出现的，出现好几次。

**Comment by dmiller-nmap** [comment]
Thanks for pointing this out. We do not frequently build the Debug configuration of Npcap, but I had it on my list of things to do this week. These assertions were failing because we failed to set the `AdapterBindingStatus` to `FilterPaused` at the end of `NPF_AttachAdapter()`.
