### ISSUE TITLE
Npcap installer disables networking for a short time during installation on Windows Server 2019

### ISSUE THREAD

**Issue by seladb** [nmap/npcap#215]
I'm the maintainer of [PcapPlusPlus](https://github.com/seladb/PcapPlusPlus) which supports Npcap as one of the packet capture engines. When setting up the [Windows CI via AppVeyor](https://github.com/seladb/PcapPlusPlus/blob/master/appveyor.yml) I noticed that the CI job fails during Npcap silent installer on Windows Server 2019, but works on older Windows Server versions. I reached out to the AppVeyor team in https://github.com/appveyor/ci/issues/3491 and they advised to use [AppVeyor RDP](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/) to look into it. When I did that I noticed that during Npcap install (both silent and GUI) RDP loses connectivity for a few seconds and then connectivity is restored. I'm not sure why this happens and if there is any workaround to avoid this. Could you please advise?

Reproducing this issue is easy: 
- Set up an AppVeyor job with `Visual Studio 2019` image (which runs on Windows Server 2019)
- In `appveyor.yml`  set up RDP as I did [here](https://github.com/seladb/PcapPlusPlus/blob/ci-test3/appveyor.yml) 
- When the job runs connect with any RDP client (including Windows "Remote Desktop" util) to the `IP:Port` shown in the CI job logs ([here](https://ci.appveyor.com/project/seladb/pcapplusplus/builds/34317175) is an example)
- From within the RDP session try to install any Npcap version. I've tried both v0.96 and v0.9995. I've also tried both silent and GUI installers, both cause the same issue

**Comment by dmiller-nmap** [comment]
This is a known issue with NDIS filter drivers. Microsoft may fix it in future versions of Windows 10 and related Server OS. See #53.
