### ISSUE TITLE
Deprecated pcap_lookupdev() returns '\'

### ISSUE THREAD

**Issue by ardikars** [nmap/npcap#220]
# Step to reproduce

`$ vim app.c`

```bash
#include <stdio.h>
#include <pcap.h>

int main() {
  char errbuf[256];
  char *dev = pcap_lookupdev(errbuf);
  printf("%s\n", dev);
  printf("%s\n", errbuf);
  return 0;
}
```

`$ gcc app.c -o app -lwpcap`
```
\

```

# Npcap Version

Installed from npcap-0.9995.exe

# Mingw64 Version

x86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z

**Comment by gvanem** [comment]
Try `printf("%S\n", dev);` instead.
You better test for Ascii/Widechar first.

**Comment by guyharris** [comment]
`pcap_lookupdev()` is not a good routine to use even on UN\*Xes, as it's not thread-safe - and, for a long time, has just been a wrapper around `pcap_findalldevs()` that returns the first device on the list, so you can just use `pcap_findalldevs()`.

`pcap_lookupdev()` has traditionally been worse on Windows - on Windows 9x, it returned a buffer with a sequence of null-terminated device names, with the device names being in the local code page ("ANSI"), followed by a sequence of null-terminated device descriptions, again in the local code page, but, on Windows NT, it returns a buffer with a sequence of null-terminated device names, with the device names being in little-endian UTF-16 ("Unicode"), followed by a sequence of null-terminated device descriptions *in the local code page*.

And it is unknown whether there were programs that depended on `pcap_lookupdev()` getting a list of devices, or on returning them in UTF-16, so it was unknown whether it could be fixed.

Furthermore, the "names are in UTF-16" mess means that `pcap_open_live()` and, later `pcap_create()`, had to do special hacks on Windows to try to detect UTF-16 device names - and those hacks run the risk of running past the end of the device name.

So `pcap_lookupdev()` is deprecated for several good reasons.  Don't use it.

**Comment by ardikars** [comment]
Thanks @gvanem @guyharris
