### ISSUE TITLE
[Npcap] Realtek Adapter SetInterface error 50

### ISSUE THREAD

**Issue by manasan3010** [nmap/npcap#225]
OS | Windows 10 x64
Npcap | npcap-0.992
Adapter | Realtek RTL8812BU USB Wireless Adapter

I'm trying to set my adapter in monitor mode, wireshark isn't showing the checkbox so I tried Wlanhelper.exe which gives Error: SetWlanOperationMode::SetInterface error, error code = 50 (The request is not supported)

I checked the supported adapters list but it's not showing any information regarding this chipset. I bought this adapter after confirmation by the seller that it supports monitor mode so I am a little bit confused.
I also want to know whether I can use aircrack-ng instead of npcap in windows for enabling monitor mode?

**Comment by dmiller-nmap** [comment]
Error code 50 is ERROR_NOT_SUPPORTED. Your network card's driver does not support monitor mode. Installing a different driver may help, as well as upgrading to Npcap 1.30, which fixes wifi frame capture on supported devices.
