### ISSUE TITLE
continuous integration with npcap

### ISSUE THREAD

**Issue by Trolldemorted** [nmap/npcap#227]
Since the npcap installer has no silent mode, it can not be used to set up npcap in the CI setup of the [rust pcap bindings](https://github.com/ebfull/pcap/pull/117#issuecomment-681495849).

Is there any chance you could support github actions somehow? Only testing against winpcap would significantly decrease the efficacy of the tests.

**Comment by fyodor** [comment]
Hi @Trolldemorted .  Yes, we would be happy to help, and we already work with open source pcap bindings for other languages to enable this.  Please email me (or ask the appropriate person to email me) at fyodor@nmap.org so we can set this up!

**Comment by GyulyVGC** [comment]
> Hi @Trolldemorted . Yes, we would be happy to help, and we already work with open source pcap bindings for other languages to enable this. Please email me (or ask the appropriate person to email me) at [fyodor@nmap.org](mailto:fyodor@nmap.org) so we can set this up!

I have a similar problem!

I developed a packet sniffer and I would like to integrate npcap on the GitHub workflow. I already sent you an email last week.

Thanks in advance!
