### ISSUE TITLE
NPCAP kills VPN and Remote Access Connection Manager

### ISSUE THREAD

**Issue by rhampong** [nmap/npcap#228]
To use Wireshark, I installed NPCAP in WNPCAP compatibility mode.
It killed my Hideme.VPN service. Uninstalling NPCAP does not fix the issue.

If you are unlucky enough NOT to have a System Restore Point before NPCAP install,
then you are thoroughly stuck with no way of recovering other than a reinstall of Windows.
What I noticed was that NPCAP stops the windows  local service:  Remote Access Connection Manager from running and also prevents it from running. Forever.  Thus the Hideme.VPN service can never start.

  SFC, all other searched tips to get Remote Access Connection Manager working again have failed.

**Comment by dmiller-nmap** [comment]
Duplicate #112

**Comment by rhampong** [comment]
so I installed NPCAP on an very old Win 7 desktop and also installed Hideme VPN  with absolutely no issues compared to my Toshiba Win 8.1 laptop
