### ISSUE TITLE
win7 npcap & it's DNS settings

### ISSUE THREAD

**Issue by FoLkjF** [nmap/npcap#230]
i've installed nmap v7.80 awhile back. i noticed when i do "nsloookups" the DNS server referenced is like, 10.101.0.243 and 185.93.180.13, 162.252.172.57, 149.154.159.92, etc. the npcap is set to get dns auto but my wired eth interface is static for my local lan dns but would pull dns requests from the odd loopback dns servers.

i've had to set them all back to my local dns servers as static. 

why does nmap npcap loopback  get these dns servers and not my local dhcp issued dns servers?  maybe they are getting these from vpn's running or?

**Comment by dmiller-nmap** [comment]
When you select the "Legacy loopback" option in the installer, we install the Microsoft KM-TEST loopback adapter and rename it "Npcap Loopback Adapter." Beyond this, we do not make any configuration changes such as adding DNS servers or setting DHCP or static addresses. However, this is often enough of a change to disrupt VPN and other security and communication software. This is why we removed the need for the separate adapter in Npcap 0.9983. The only reason to enable this option currently is for loopback scanning with Nmap, and we hope to have a release of Nmap out this month that will work without the loopback adapter as well.

Our recommendation is to reinstall without the "Legacy loopback" option and remove any remaining loopback adapters that may have been left behind by older, buggy installers (#55). If the problem persists, you may reopen this issue.
