### ISSUE TITLE
Npcap error 8007007e

### ISSUE THREAD

**Issue by JuanFazbear** [nmap/npcap#232]
i need help
i cant download npcap with the error 8007007e
![image](https://user-images.githubusercontent.com/68427503/92424856-aea76c00-f1af-11ea-951e-6ca0073fd4eb.png)
please answer and
GIVE DETAILS ABOUT HOW TO FIX IT!

**Comment by dmiller-nmap** [comment]
Thanks for this report. I am consolidating all instances of error 8007007e (ERROR_MOD_NOT_FOUND) at #135. Please check that issue for potential workarounds or fixes.
