### ISSUE TITLE
Bluescreen installing/unistalling Npcap 0.9997

### ISSUE THREAD

**Issue by lemitpO** [nmap/npcap#234]
When I tried to install Npcap It will give me a bluescreen when I'm installing it. When I go and try to uninstall I get the same issue.

allready tried disabling my Virus scanner but didnt help.

**Comment by fyodor** [comment]
@lemitpO - Since you closed the issue, I assume it has been resolved.  But if you have time, can you leave a comment nothing the resolution?  Maybe it could help someone else.  Cheers!
