### ISSUE TITLE
Qualify WMIC.exe path when called by CheckStatus.bat

### ISSUE THREAD

**Issue by fyodor** [nmap/npcap#236]
I received an excellent report by email recently from Jimmy Bayne (@bohops) noting that the Npcap watchdog calls the Windows WMIC.exe tool by relying on the Windows directory search order rather than specifying the System32\Wbem directory explicitly.  This is not a vulnerability by default since Windows ships with a PATH that searches these Windows directories first.  However, some (idiotic) Windows software creates directories writable by unprivileged users AND adds those directories to the front of the search path even before the Windows directories.  In such a case, a malicious unprivileged user could put their own trojan WMIC.exe in the new with elevated privileges without qualifying it with the directory name and then have it be executed by the Npcap watchdog in elevated privilege context.

Even though this is a hole opened by careless and insecure software rather than a flaw in Npcap, we can still do our best to mitigate it.  Probably the easiest way is to explicitly call WMIC.exe from System32\Wbem, assuming it is always in that location (we should verify).  We could use a command like:

%SystemRoot%\System32\wbem\wmic.exe nic GET Name,NetConnectionID | find "Npcap Loopback Adapter"

Note that the reason for these world-writeable directories is often another Windows weakness--for compatability reasons (I guess), Windows tends to default to making new subdirectories from C:\ world writeable.  So software that installs itself under c:\SoftwareName rather than in the normal "Program Files" subdir often ends up with its install directory world writeable.

Note that this problem does not affect other programs our watchdog calls like REG.exe because those are directly under System32 instead of System32\Wbem and Microsoft gives that dir special treatment to avoid the Windows $PATH search order mess.  They should probably be consistent and do this with all Windows system directories.

Another solution would be to remove the Npcap watchdog feature entirely.  Unfortunately, there is a history of Windows "Feature Releases" breaking Npcap in a specific way--they remove the driver's auto-start feature.  We have reproduced this with other Windows drivers (including an official Microsoft sample driver) as well.  The watchdog detects the problem and fixes it automatically.  So if we remove it, there is a risk that everyone's Npcap installs could be hosed form a future update.  And that's no fun.

**Comment by csadam** [comment]
@dmiller-nmap  @bonsaiviking  The fix of this issue contains wrong path `"%SYSTEMROOT%\wbem\wmic.exe"` while the correct path is `"%SYSTEMROOT%\System32\wbem\wmic.exe"`
Because of this, currently the CheckStatus.bat does not work and stops with error because it can not find the wmic.exe.

**Comment by fyodor** [comment]
@csadam - Good catch.  Re-opening and we're working on fixing this.
