### ISSUE TITLE
Npcap SDK 1.05's Packet.lib doesn't export PacketGetTimestampModes()

### ISSUE THREAD

**Issue by guyharris** [nmap/npcap#240]
CMake doesn't find `PacketGetTimestampModes()` in the SDK's Packet.dll, and dumpbin/exports, when run on Packet.dll, doesn't show `PacketGetTimestampModes()`.

This will prevent libpcap from using it, as we'll be doing a CMake test to check whether it's present.

**Comment by dmiller-nmap** [comment]
Thanks for pointing that out. Npcap SDK 1.06 is up on the website now; `PacketGetTimestampModes()` is the only change.

**Comment by guyharris** [comment]
Speaking of SDKs, once there's an Npcap release with a version number > the SDK version number, should subsequent SDK version numbers track the Npcap version number (and new SDKs released with each Npcap release)?
