### ISSUE TITLE
BIOCGTIMESTAMPMODES doesn't set the first element of the array of modes to the count of modes

### ISSUE THREAD

**Issue by guyharris** [nmap/npcap#241]
How do you determine the number of modes that are available, so that a buffer can be allocated to store the modes?

**Comment by guyharris** [comment]
At least one problem is that the driver code for `BIOCGTIMESTAMPMODES` isn't returning the count of modes.

The code in Packet.c that handles `BIOCGETPIDS` ends with

    *pUL = cnt;

The code that handles `BIOCGTIMESTAMPMODES` does not.

**Comment by dmiller-nmap** [comment]
I'm sorry, I rushed this bit of code to try to give you a head start on the libpcap end of things, and I missed this bit. Correction to this and #243 is incoming.

**Comment by guyharris** [comment]
> I'm sorry, I rushed this bit of code to try to give you a head start on the libpcap end of things,

It did - I wouldn't have found the bugs if I didn't have libpcap code to use it. :-)  Thanks.
