### ISSUE TITLE
BIOCGTIMESTAMPMODES appears to overflow the buffer if it's one ULONG and that ULONG is set to 1

### ISSUE THREAD

**Issue by guyharris** [nmap/npcap#243]
With this version of `pcap_create_interface()` in pcap-npf.c:

    pcap_t *
    pcap_create_interface(const char *device _U_, char *ebuf _U_)
    {
    	pcap_t *p;
    #ifdef HAVE_PACKET_GET_TIMESTAMP_MODES
    	char *device_copy;
    	ADAPTER *adapter;
    	ULONG num_ts_modes;
    	BOOL ret;
    	DWORD error;
    	ULONG *modes;
    #endif
    
    	p = PCAP_CREATE_COMMON(ebuf, struct pcap_win);
    	if (p == NULL)
    		return (NULL);
    
    	p->activate_op = pcap_activate_npf;
    	p->can_set_rfmon_op = pcap_can_set_rfmon_npf;
    
    #ifdef HAVE_PACKET_GET_TIMESTAMP_MODES
    	/*
    	 * First, find out how many time stamp modes we have.
    	 * To do that, we have to open the adapter.
    	 *
    	 * XXX - PacketOpenAdapter() takes a non-const pointer
    	 * as an argument, so we make a copy of the argument and
    	 * pass that to it.
    	 */
    	device_copy = strdup(device);
    	adapter = PacketOpenAdapter(device_copy);
    	free(device_copy);
    	if (adapter != NULL)
    	{
    		/*
    		 * Get the total number of time stamp modes.
    		 *
    		 * The buffer for PacketGetTimestampModes() is
    		 * a sequence of 1 or more ULONGs.  What's
    		 * passed to PacketGetTimestampModes() should have
    		 * the total number of ULONGs in the first ULONG;
    		 * what's returned *from* PacketGetTimestampModes()
    		 * has the total number of time stamp modes in
    		 * the first ULONG.
    		 *
    		 * Yes, that means if there are N time stamp
    		 * modes, the first ULONG should be set to N+1
    		 * on input, and will be set to N on output.
    		 *
    		 * We first make a call to PacketGetTimestampModes()
    		 * with a pointer to a single ULONG set to 1; the
    		 * call should fail with ERROR_MORE_DATA (unless
    		 * there are *no* modes, but that should never
    		 * happen), and that ULONG should be set to the
    		 * number of modes.
    		 */
    		num_ts_modes = 1;
    		ret = PacketGetTimestampModes(adapter, &num_ts_modes);
    		if (!ret) {
    			/*
    			 * OK, it failed.  Did it fail with
    			 * ERROR_MORE_DATA?
    			 */
    			error = GetLastError();
    			if (error != ERROR_MORE_DATA) {
    				/*
    				 * No, some other error.  Fail.
    				 */
    				pcap_fmt_errmsg_for_win32_err(ebuf,
    				    PCAP_ERRBUF_SIZE, GetLastError(),
    				    "Error calling PacketGetTimestampModes");
    				pcap_close(p);
    				return (NULL);
    			}
    
    #if 1
    			/* XXX work around Npcap bug for quick testing */
    			num_ts_modes = 3;	/* This is on W10, so 3 modes */
    #endif
    			/*
    			 * Yes, so we now know how many types to fetch.
    			 *
    		    	 * The buffer needs to have one ULONG for the
    		    	 * count and num_ts_modes ULONGs for the
    		    	 * num_ts_modes time stamp types.
    		    	 */
    			modes = (ULONG *)malloc((1 + num_ts_modes) * sizeof(ULONG));
    			if (modes == NULL) {
    				/* Out of memory. */
    				/* XXX SET ebuf */
    				pcap_close(p);
    				return (NULL);
    			}
    			modes[0] = 1 + num_ts_modes;
    			if (!PacketGetTimestampModes(adapter, modes)) {
    				pcap_fmt_errmsg_for_win32_err(ebuf,
    				    PCAP_ERRBUF_SIZE, GetLastError(),
    				    "Error calling PacketGetTimestampModes");
    				free(modes);
    				pcap_close(p);
    				return (NULL);
    			}
    #if 1
    			/* XXX work around Npcap bug for quick testing */
    			modes[0] = 3;	/* This is on W10, so 3 modes */
    #endif
    			if (modes[0] != num_ts_modes) {
    				snprintf(ebuf, PCAP_ERRBUF_SIZE,
    				    "First PacketGetTimestampModes() call gives %lu modes, second call gives %u modes",
    				    num_ts_modes, modes[0]);
    				free(modes);
    				pcap_close(p);
    				return (NULL);
    			}
    			if (num_ts_modes != 0) {
    				u_int num_ts_types;
    
    				/*
    				 * Allocate a buffer big enough for
    				 * PCAP_TSTAMP_HOST (default) plus
    				 * the explicitly specified modes.
    				 */
    				p->tstamp_type_list = malloc((1 + modes[0]) * sizeof(u_int));
    				if (p->tstamp_type_list == NULL) {
    					/* XXX SET ebuf */
    					free(modes);
    					pcap_close(p);
    					return (NULL);
    				}
    				num_ts_types = 0;
    				p->tstamp_type_list[num_ts_types] =
    				    PCAP_TSTAMP_HOST;
    				num_ts_types++;
    				for (ULONG i = 0; i < modes[0]; i++) {
    					switch (modes[i + 1]) {
    
    					case TIMESTAMPMODE_SINGLE_SYNCHRONIZATION:
    						/*
    						 * Better than low-res,
    						 * but *not* synchronized
    						 * with the OS clock.
    						 */
    						p->tstamp_type_list[num_ts_types] =
    						    PCAP_TSTAMP_HOST_HIPREC_UNSYNCED;
    						num_ts_types++;
    						break;
    
    					case TIMESTAMPMODE_QUERYSYSTEMTIME:
    						/*
    						 * Low-res, but synchronized
    						 * with the OS clock.
    						 */
    						p->tstamp_type_list[num_ts_types] =
    						    PCAP_TSTAMP_HOST_LOWPREC;
    						num_ts_types++;
    						break;
    
    					case TIMESTAMPMODE_QUERYSYSTEMTIME_PRECISE:
    						/*
    						 * High-res, and synchronized
    						 * with the OS clock.
    						 */
    						p->tstamp_type_list[num_ts_types] =
    						    PCAP_TSTAMP_HOST_HIPREC;
    						num_ts_types++;
    						break;
    
    					default:
    						/*
    						 * Unknown, so we can't
    						 * report it.
    						 */
    						break;
    					}
    				}
    				p->tstamp_type_count = num_ts_types;
    				free(modes);
    			}
    		}
    		PacketCloseAdapter(adapter);
    	}
    #endif /* HAVE_PACKET_GET_TIMESTAMP_MODES */
    
    	return (p);
    }
    
with a DEBUG build, I get a dialog popping up that says that there was something overwritten on the stack near `num_ts_modes`.

If I replace the definition of `num_ts_modes` with

    	ULONG dont_overflow_me[16];
    #define num_ts_modes dont_overflow_me[0]

I don't get that diagnostic.

**Comment by guyharris** [comment]
The same thing happens if I use the `don't_overflow_me` array but give it only one element.

**Comment by dmiller-nmap** [comment]
The "overflow" isn't actually writing anything there, it's just the IoCtl handler *declaring* that it has written more bytes than the buffer contains. I had set the `Information` element to the number of bytes we *would* have written  if the buffer had been big enough. Instead, I should set this to the number of bytes we *actually* wrote, which is never going to be more than the number of bytes provided in the DeviceIoControl call.

**Comment by guyharris** [comment]
So whatever code in the debug build that popped up the dialog was trusting the `DeviceIoControl()` "bytes returned" value to be the number of bytes returned, and was doing a check based on that?  I was wondering about that, as I didn't see anything in the driver that looked suspicious, other than the code that set `Information` (I hadn't dug deeply enough into the driver documentation to see where that field was used).
