### ISSUE TITLE
BSOD every time I try to install Npcap 1.00 on Windows 10

### ISSUE THREAD

**Issue by gianmaxfactor** [nmap/npcap#244]
I used the following flags:

Legacy support YES
Restrict to admins NO
Support 802.11 NO
API-compatible YES

After some seconds the start of the installation I get a BSOD with Stop code: SYSTEM SERVICE EXCEPTION

Which other info can I collect and send?

**Comment by bubbasnmp** [comment]
https://twitter.com/cpu4coffee/status/1309882783242883073  
Is there an older version already loaded on the machine?
If so, remove it manually (Windows settings) then try 1.0.

**Comment by gianmaxfactor** [comment]
You are the man! Thank you Bubba!
