### ISSUE TITLE
Error while capturing packets

### ISSUE THREAD

**Issue by farmid** [nmap/npcap#251]
![wireshark](https://user-images.githubusercontent.com/60242496/95250383-e44f6d00-07ce-11eb-851b-916f597c9594.png)

The message says "while...the device removed"

No devices was removed while monitoring.

**Comment by guyharris** [comment]
See also #250.

**Comment by captainretro01** [comment]
im #250

**Comment by dmiller-nmap** [comment]
Duplicate #250
