### ISSUE TITLE
Tap devices, bridge and npcap on Windows 10

### ISSUE THREAD

**Issue by tdelsin** [nmap/npcap#266]
Hello !

I'm using TAP devices for 2 Virtual machines running over Windows 10. The 2 VM use pcap and work as a charm.
If i try to link them with a Microsoft bridge, they disapppears from the ncap list and, therefore, are no more usable by the 2 VM :-(

Here is the result of the Wireshark "dumpcap -D" command when both TAP devices are part of the bridge

_

> C:\Program Files (x86)\Wireshark>dumpcap -D
> 1. \Device\NPF_{BCFA3D6E-7423-4E80-AA12-290F0D45C04F} (eLNXnic)
> 2. \Device\NPF_{77B68562-92B2-4805-BA09-7A9206AE7F7E} (Pont reseau)
> 3. \Device\NPF_{C337773A-1FCA-4162-BE93-533E4A57F06B} (Connexion au reseau local* 8)
> 4. \Device\NPF_{7C592341-EE5F-4FC3-9326-91952401DA8F} (Connexion au reseau local* 1)
> 5. \Device\NPF_{C1C32D81-D897-4F4F-8A9A-D6591CAA80FE} (Wi-Fi)
> 6. \Device\NPF_{AF1904EE-5B45-4B8E-8F70-D8EDAD64BCC0} (VirtualBox Host-Only Network)
> 7. \Device\NPF_{002CA644-DC13-4BCA-AC44-7AC3861687F4} (Connexion au reseau local* 2)
> 8. \Device\NPF_{E65DFB27-53C0-41BC-B3AC-21735444AAB7} (Connexion au reseau local* 9)
> 9. \Device\NPF_{EC046243-C3A1-4F46-B0FC-75D413C7CC08} (eAXPnic)
> 10. \Device\NPF_{8F56A907-D0CB-4741-959A-EBAB8BB037B8} (Connexion au reseau local* 10)
> 11. \Device\NPF_{B26BA317-A253-4072-AEED-5492A1099D49} (Ethernet)
> 12. \Device\NPF_{354CD307-3C8C-406D-A9DE-713E908A2080} (eVAXnic)
> 13. \Device\NPF_Loopback (Adapter for loopback traffic capture)

_

And the result of the same command when one TAP device called eDUMnic is removed from the bridge.

_

> C:\Program Files (x86)\Wireshark>dumpcap -D
> 1. \Device\NPF_{BCFA3D6E-7423-4E80-AA12-290F0D45C04F} (eLNXnic)
> 2. \Device\NPF_{77B68562-92B2-4805-BA09-7A9206AE7F7E} (Pont reseau)
> 3. \Device\NPF_{C337773A-1FCA-4162-BE93-533E4A57F06B} (Connexion au reseau local* 8)
> 4. \Device\NPF_{7C592341-EE5F-4FC3-9326-91952401DA8F} (Connexion au reseau local* 1)
> 5. \Device\NPF_{C1C32D81-D897-4F4F-8A9A-D6591CAA80FE} (Wi-Fi)
> 6. \Device\NPF_{AF1904EE-5B45-4B8E-8F70-D8EDAD64BCC0} (VirtualBox Host-Only Network)
> 7. \Device\NPF_{002CA644-DC13-4BCA-AC44-7AC3861687F4} (Connexion au reseau local* 2)
> 8. \Device\NPF_{E65DFB27-53C0-41BC-B3AC-21735444AAB7} (Connexion au reseau local* 9)
> 9. \Device\NPF_{EC046243-C3A1-4F46-B0FC-75D413C7CC08} (eAXPnic)
> 10. \Device\NPF_{8F56A907-D0CB-4741-959A-EBAB8BB037B8} (Connexion au reseau local* 10)
> 11. \Device\NPF_{B26BA317-A253-4072-AEED-5492A1099D49} (Ethernet)
> 12. \Device\NPF_{354CD307-3C8C-406D-A9DE-713E908A2080} (eVAXnic)
> **13. \Device\NPF_{9187A065-F285-486C-8E66-6A2AC5A48839} (eDUMnic)**
> 14. \Device\NPF_Loopback (Adapter for loopback traffic capture)

_
 
Thank in advance for your help

I apologize for my awful english.

**Comment by dmiller-nmap** [comment]
Thanks for this report. I am looking into Npcap's behavior with regard to network bridges. This issue has been previously reported and described at #115, so I am closing this issue to consolidate the discussion.
