### ISSUE TITLE
Npcap 0.9985 - 0.9988 BSoD crash when upgrading to Npcap 0.9996 or later

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/npcap#268]
Issue nmap/nmap#1924, fixed in Npcap 0.9989, can be triggered when upgrading to Npcap 0.9996 or later, resulting in a blue screen system crash.

The recommended workaround is to directly uninstall the existing Npcap installation prior to running the newer installer.

The fix will be to change the version number check in the installer to 0.9989 or later when unpacking the upgrade uninstaller. Versions prior to 0.9989 will be uninstalled using the existing uninstaller.

**Comment by joelOttawa** [comment]
Thanks for the wonderful software.   FYI, current downloads as of today 2021-01-12 (both npcap 1.00 included with Wireshark 3.4.2, and npcap 1.10 from npcap github) still gave me BSOD (sorry, minidump not available) on Windows 10 with existing npcap 0.9987 from an earlier Wireshark install.  Per your advice in https://github.com/nmap/npcap/issues/253, I ran "sc.exe config npcap start= disabled", rebooted, and then successfully updated npcap.   Also, command "msinfo32" was useful to verify the driver status.
