### ISSUE TITLE
Is npcap supported in a docker windows container?

### ISSUE THREAD

**Issue by reveillesoftware** [nmap/npcap#269]
Is npcap supported in a docker windows container?

**Comment by fyodor** [comment]
I have not specifically heard of any problems using Npcap in docker Windows containers.  I use it in virtual machines all of the time, though that technology is a bit different.  Have you tried it?  I'm closing this issue, but anyone is welcome to open a new one if you discover any problems running Nmap in a Windows Docker Container.  Please include pertinent software configuration details in the report.  Cheers!
