### ISSUE TITLE
NPCAP installation failing with error "0x800f0203: Couldn't install the network component."

### ISSUE THREAD

**Issue by abhinku6** [nmap/npcap#272]
NPCAP installation is failing with error "0x800f0203: Couldn't install the network component."
Possible cause:

There is no driver selected for the device information set or element.

The version, I am trying to install is .991. I have tried .9990 but that also fails.
Attaching the logs.
[NPFInstall.log](https://github.com/nmap/npcap/files/5703390/NPFInstall.log)
[install.log](https://github.com/nmap/npcap/files/5703392/install.log)
[setupapi.dev.log](https://github.com/nmap/npcap/files/5703395/setupapi.dev.log)

**Comment by abhinku6** [comment]
Cleaning old binaries fixed the problem. Closing the issue.

**Comment by guyharris** [comment]
> Cleaning old binaries fixed the problem.

Which old binaries?  It might be possible to detect the problem, and possibly fix it, for example by removing out-of-date binary files.
