### ISSUE TITLE
npcap installation creates npcapwatchdog task even though loopback not selected.

### ISSUE THREAD

**Issue by plaintextcity** [nmap/npcap#274]
I reported this to Wireshark, they directed me to open the issue as the npcap installation is causing it.  Note that Wireshark is callign the npcap 1.0 installation.

https://gitlab.com/wireshark/wireshark/-/issues/17117

## Summary

When installing Wireshark 3.4.2, the installation process called schtasks to schedule a task to make sure the loopback adapter is enabled if it was requested.  As the loopback adapter was not requested, no loopback.ini was created, so this scheduled task does nothing but run at every boot.

## Steps to reproduce

When install Wireshark 3.4.2 and don't request loopback adapter.

## What is the current bug behavior?

Scheduled task to check if the loopback adapter was requested, and if so re-enable it, is configured to run at every system boot.

Organizations that watch for unexpected scheduled tasks may see this as potentially suspicious behavior and need to investigate.

## What is the expected correct behavior?

Don't schedule the npcapwatchdog task unless the user has requested the loopback adapter installation.

## Sample capture file

You can see the task is present by running 

```
schtasks /tn npcapwatchdog
```

You can delete the task by running

```
schtasks /delete /tn npcapwatchdog
```

## Relevant logs and/or screenshots

```
(Paste any relevant logs here)
```
(Paste any relevant screenshots here)

## Build information
```
Wireshark Version 3.4.2 (v3.4.2.0-ga889cf1b1bf9)
```

**Comment by dmiller-nmap** [comment]
Thanks for the report. This was indeed the only purpose of the `npcapwatchdog` scheduled task prior to Npcap 1.10. We changed its behavior in that release to instead check for the start type of the `npcap` kernel driver service, since that is what Windows 10 changes as part of installing a Feature Update.

Closing this since the watchdog task is no longer related to loopback capture.
