### ISSUE TITLE
libpcap 1.10 has been released

### ISSUE THREAD

**Issue by guyharris** [nmap/npcap#276]
It contains a number of changes, including some that have been backported to Npcap's libpcap; see t[he CHANGES file](https://github.com/the-tcpdump-group/libpcap/blob/master/CHANGES).

Some Windows changes include:

- report the system error for `PacketSetHwFilter()` failures;
- add support for getting and setting packet time stamp types with Npcap;
- add pcap_init(), and add support for UTF-8 strings, including error messages, on Windows;
- make the snapshot length work even if `pcap_setfilter()` isn't called (backported, I think);
- add `pcap_handle()`, and deprecate `pcap_fileno()`;
- report PCAP_ERROR_NO_SUCH_DEVICE for a non-existent device;
- handle CRT mismatch for `pcap_dump_fopen()` (done by making it a macro wrapper - the Universal CRT can't sweep the Windows world fast enough...);
- map NdisMediumWirelessWan to DLT_RAW (backported);
- report a warning for unknown link-layer header types;

and one I missed - `pcap_breakloop()` on Windows now sets the event for the `pcap_t`, so even if the capturing thread is blocked waiting for packets to arrive, it will be woken up if `pcap_breakloop()` is called in another thread.

**Comment by dmiller-nmap** [comment]
c3c1acee5c802365476881d63a904b18f7a6015b  points our submodule to our fork of libpcap 1.10, which currently represents the libpcap-1.10 branch, including unreleased commits from the-tcpdump-group. We would prefer to use a pristine release tag, but there are important updates there that we need for testing at the  moment. Remaining tasks:

- [ ] Build documentation using roffit, upstreaming formatting changes if necessary.
- [ ] Build new version of Npcap SDK to include wpcap.lib and the most recent pcap.h.
- [ ] Make sure our build generates and packages debug symbols for wpcap.dll.

**Comment by dmiller-nmap** [comment]
Npcap 1.20 and later include libpcap 1.10. Use Npcap SDK 1.07 or later to build software with the libpcap 1.10 API headers.
