### ISSUE TITLE
Unable to access internet without restarting

### ISSUE THREAD

**Issue by Eleos5** [nmap/npcap#281]
I downloaded wireshark and am using version 1.00 of npcap. After doing so I was unable to access the internet without restarting my computer. Sleep mode didn't keep the fix. "unidentified network" is all that would greet me.

**Comment by sky5454** [comment]
same with https://github.com/nmap/npcap/issues/263#issue-748164269, reset the adapt then work.
if you extremely dependent on it, I sugguest you use https://github.com/SoftEtherVPN/Win10Pcap/ to replace it.

It seems that the npcap' team has  **no intention** of solving this problem.

**Comment by phunsoft** [comment]
...and possibly same problem with [issue #278](https://github.com/nmap/npcap/issues/278). I'm still using WimPCap 4.1.3 on Win 10. Will try Win10Pcap eventually. npcap is gone for me, at least for the time being.

**Comment by sqwwqw5** [comment]
I've met this issue using 1.7 as well, this seems pretty serious, any update?

**Comment by fyodor** [comment]
Hi @sqwwqw5.  I believe this issue was fixed more than a year ago (closing it now), so what you are seeing is probably a different issue with similar symptoms.  Would you please create a new issue describing exactly what happened?  Thanks!
