### ISSUE TITLE
Multiple npcap versions in parallel for testing

### ISSUE THREAD

**Issue by pstavirs** [nmap/npcap#288]
Is it possible to have multiple npcap versions installed in parallel for testing purposes? If so, how to install in separate locations and determine which to activate?

Specifically, I have an application that uses npcap and I'm getting reports of behaviour difference between users using different npcap versions and I would like to test this on my development machine.

**Comment by dmiller-nmap** [comment]
It is not possible to install different versions of Npcap on the same machine. The Packet.dll and Npcap driver must be the same version as each other to ensure compatibility, and there cannot be multiple drivers with the same name on a single machine. To test different versions of Npcap, we recommend using VM snapshots or separate machines. If you have specific questions regarding behavior differences that are not discussed in the Changelog, please let us know and we will investigate.
