### ISSUE TITLE
Upgrade installer from NSIS 2 to NSIS 3

### ISSUE THREAD

**Issue by fyodor** [nmap/npcap#292]
Npcap's and Npcap OEM's current installers are generated by the Nullsoft NSIS 2 installer system, and we want to upgrade to NSIS 3.  NSIS 2 has been deprecated for a long time, and we're having some application compatibility issues that NSIS might help to resolve.  In particular we had a report about Npcap OEM installation failing for a customer who disabled the Windows "Application Experience" service on their Windows Server 2012 systems.

**Comment by dmiller-nmap** [comment]
Npcap 1.20 installer is built with NSIS 3.
