### ISSUE TITLE
Uninstalling  0.9997, windows Server 2016 crashes to reboot

### ISSUE THREAD

**Issue by valdr** [nmap/npcap#295]
I am attempting to uninstall npcap 0.9997 but all it does is crash the Vmware instance of Windows server 2016 it is installed on.
I have attempted to install the latest version, but this too only crashes the server.

Is there any log/system resource I should check for a clue why it is crashing?
My apologies for the lack of detail.

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. This is not a known issue, unless it is possible that the upgrade to 0.9997 didn't happen cleanly, leaving an even older Npcap that suffers from the bug in #280. Until we release an installer that can detect and handle such issues, the recommended workaround is to stop the Npcap driver service prior to uninstalling or upgrading. You can do this by starting a command prompt as Administrator and running `net stop npcap`. If this does not resolve the issue, then please send the most recent crash dump from `C:\Windows\Minidump\` to dmiller@nmap.com and we will debug it.

**Comment by valdr** [comment]
C:\Windows\system32>net stop npcap
The Npcap Packet Driver (NPCAP) service was stopped successfully.
C:\Windows\system32>

I then ran add/remove programs and was finally succesful in uninstalling NPCAP OEM. 

Thank you, @dmiller-nmap.

**Comment by dmiller-nmap** [comment]
Npcap 1.20 installer ought to avoid this issue going forward. Closing.
