### ISSUE TITLE
After installing npcap-1.30, wireshark can only capture the loopback package

### ISSUE THREAD

**Issue by BruceBeanSun** [nmap/npcap#302]
After npcap-1.30 is installed on Windows 10, the list of Wireshark network cards is as shown in the picture. 
![微信图片_20210413144902](https://user-images.githubusercontent.com/19485769/114512756-06d5ad80-9c6c-11eb-8df9-38fbd6c61634.png)

Many additional network cards are added, and the link layer headers of all network cards are changed to loopback. As a result, no matter which network card is selected,  can only capture the loopback packets。

**Comment by BruceBeanSun** [comment]
The same problem occurs on Windows Server 2012

**Comment by guyharris** [comment]
The sparklines (the traffic graph between the adapter name and the adapter link-layer type) look suspiciously similar; could Npcap be capturing on the exact same device, whatever that might be, for *all* of those adapters?

**Comment by BruceBeanSun** [comment]
The sparklines are the same because the traffic of these interfaces is the same. The packet captured on each adapter is exactly same, and there are only loopback packets.

**Comment by guyharris** [comment]
> The sparklines are the same because the traffic of these interfaces is the same.

That's a tautology, because what the the sparklines are displaying *is* the traffic.

The question is why the traffic on all of the interfaces is the same; my question is whether Npcap might, somehow, be tapping the same underlying device (its special loopback adapter) for all of them?

**Comment by dmiller-nmap** [comment]
This appears to be caused by a misplaced parenthesis in the comparison of an adapter name with that of the legacy Npcap Loopback Adapter retrieved from the Registry. This is resulting in every comparison being true. To fix the issue, reinstall Npcap and un-check the installation option box for "Legacy Loopback support." We will issue a bugfix release soon.
