### ISSUE TITLE
Link to issues on npcap page still directs to the nmap issues page

### ISSUE THREAD

**Issue by gbloice** [nmap/npcap#306]
On https://nmap.org/npcap/, in the section headed "Patches, Bug Reports, Questions, Suggestions, etc" has the text:

Bug reports for Npcap can also be filed on the [https://github.com/nmap/nmap/issues/](Nmap bug tracker).

And the link does go to the nmap issue page.

The text and link should be corrected to point to the npcap issue page.

**Comment by dmiller-nmap** [comment]
Thanks for pointing this out! I'll get it fixed.

**Comment by dmiller-nmap** [comment]
Done.
