### ISSUE TITLE
Npcap 1.10 Fixed npcap driver service is configured for SYSTEM_START but does not start the service

### ISSUE THREAD

**Issue by gerdwachsabb** [nmap/npcap#309]
From the change log of Npcap 1.10 Check that the npcap driver service is configured for SYSTEM_START in the npcapwatchdog scheduled task and correct it if necessary. Windows feature updates can modify this value.

This is great but it still requires manual interaction to get the service started. 
This is either command line to start the service, or to reboot the computer.

Request: Please have the npcapwatchdog also start the service if it is not already running.

**Comment by dmiller-nmap** [comment]
The npcapwatchdog task runs at startup. If the start type is not SYSTEM_START, the FixInstall.bat script is run to correct that. That script always ends by starting the npcap service, so there is nothing to change there. If the start type is SYSTEM_START and the service is not started, then there is something else wrong that should probably be reported as a failure to start the service.
