### ISSUE TITLE
Wifi adapter interference

### ISSUE THREAD

**Issue by GogoAkira** [nmap/npcap#33]
On a HP EliteBook 840 G2 , Windows 10, few days after npcap is installed I always have to turn off npcap loopback adapter in order to use wifi to connect to router, it turns off by itself, clicking on turn on wifi manually lasts for half a second and then goes off again.  This does not happen imediatelly right after I install npcap but a few days after.

**Comment by dmiller-nmap** [comment]
Since we have not heard back, we will assume this issue was resolved. If this issue persists in Npcap 1.30 or later, please let us know.
