### ISSUE TITLE
Npcap 0.994 crashes with IRQL_NOT_LESS_OR_EQUAL

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/npcap#352]
This issue has resulted in at least 23 crashes reported via the Microsoft crash telemetry, and is due to a failure to check for a NULL return from `NPF_GetLoopbackOpen()`. Fix is incoming. In the meantime, it would be advisable to revert to Npcap 0.993 until a release is made.

**Comment by windisklessfree** [comment]
Working Solution https://windisklessfree.github.io/IRQL_NOT_LESS_OR_EQUAL/

**Comment by guyharris** [comment]
> Working Solution https://windisklessfree.github.io/IRQL_NOT_LESS_OR_EQUAL/

As @dmiller-nmap says, this bug is fixed in 0.996, so the Working Solution is to use Npcap 0.996 or later; given that the current Npcap, as of 2023-12-10, is 1.78, which is definitely later, "just use the current Npcap" is the Working Solution.
