### ISSUE TITLE
npcap 0.99-r9 BSOD

### ISSUE THREAD

**Issue by Oryteclin** [nmap/npcap#361]
I've installed npcap with wireshark 3.0.0. I get BSOD everytime I try to start PPPoE connection or create the new one.

**Comment by Jondoe398** [comment]
The issue likely pertains to the PPPoE dialing on Windows 7 devices. 
 I utilized the NDIS filter example from WDDK and modified the .inf file to include nolower in FilterMediaTypes.  With this configuration, there isn't a blue screen crash, but dialing does fail.  However, if nolower is removed, the driver is unable to attach to virtual devices such as WinTun…
