### ISSUE TITLE
Npcap Bug Report

### ISSUE THREAD

**Issue by sehsphare** [nmap/npcap#44]
I installed npcap with Nmap; however, it doesn't seem to be working for either Wireshark or Nmap. In Nmap I get a failed to open lo0 and in Wireshark there are no interfaces. In Nmap I simply tried to scan my ip with the default settings. In Wireshark I only opened the program. I would expect the scan to return some kind of results and for Wireshark to find my adapters. My e-mail is mezaiii.andres@gmail.com. I look forward to any help you may be able to provide.

[DiagReport-20191013-220531.txt](https://github.com/nmap/nmap/files/3722802/DiagReport-20191013-220531.txt)

**Comment by fyodor** [comment]
I'm closing this one since no updated information was provided and there is a good chance the issue has been fixed since version 0.9982.
