### ISSUE TITLE
Npcap0.9983 - windows 10 insider GSOD

### ISSUE THREAD

**Issue by snuffy44** [nmap/npcap#45]
Last several versions of Windows 10 Insider 20H1 have been causing GSOD with kernel access violations.

When I try to start wireshark and it gets the interfaces will GSOD.

[minidump.txt](https://github.com/nmap/nmap/files/3715080/minidump.txt)
[DiagReport-20191011-111305.txt](https://github.com/nmap/nmap/files/3715073/DiagReport-20191011-111305.txt)

**Comment by dmiller-nmap** [comment]
I'm going to say this is very likely not an issue with Npcap. Here is my reasoning:

1. The crash is in a Windows Insider Preview, not in any released version of Windows.
2. The OID request code has been stable for a long time without causing any crashes.
3. The only variable input to the OID_GEN_CURRENT_PACKET_FILTER set request is a single ULONG. If issuing such a request with a particular value can cause the system to bugcheck, then there is a failure in the system to correctly sanitize and reject the invalid value.

If this exact bugcheck (0x139 KERNEL_SECURITY_CHECK_FAILURE) happens again in a released version of  Windows, we will revisit this issue.
