### ISSUE TITLE
Support timestamp method selection by capture handle rather than registry key

### ISSUE THREAD

**Issue by fyodor** [nmap/npcap#46]
Operating systems have various timestamp methods available with differing tradeoffs between granularity, accuracy, precision, efficiency, etc.

Npcap has an undocumented legacy method ([inherited from Winpcap](https://www.winpcap.org/pipermail/winpcap-bugs/2010-January/001153.html)) for choosing this on a system-wide basis using TimestampMode registry key. It can be set to "0", "2", or "3":
* **0** is the default and uses KeQueryPerformanceCounter.  This provides great precision (some microseconds) but is less reliable on SMP/HyperThreading machines since it doesn't return monotonic values across multiple CPUs.
* **2** uses KeQuerySystemTime instead, which is more reliable on SMP/HyperThreading machines, with a precision of a scheduling quantum (10/15 milliseconds)
* **3** uses the i386 RDTSC instruction.  This is also less reliable on SMP/HyperThreading/SpeedStep machines and has a precision of some microseconds.

The registry location for this key depends on whether you are using Npcap native mode or Winpcap compatible:

* **HKLM\System\CurrentControlSet\Services\npcap\Parameters\TimestampMode** if using Npcap native API mode (npcap driver)
* **HKLM\System\CurrentControlSet\Services\npf\Parameters\TimestampMode** if using Winpcap compatible mode (npf driver)

It is probably best to just set both.  Also note that even the Winpcap compatible location is a bit different than what Winpcap uses (which is **HKLM\System\CurrentControlSet\Services\NPF\TimestampMode**).

We have verified that this feature works with Npcap 0.9983, but we haven't officially documented it because setting the timestamp mode system-wide is not a great approach.  It could cause issues if multiple applications are using Npcap and each wants a different mode.

The better method that we might actually want to officially support uses the per-capture handle **timestamp** option as [described here](https://nmap.org/npcap/guide/wpcap/pcap.html#timestamp).  That describes the options available on several platforms, but we don't offer any non-default options through this API on Windows (Npcap).  But we might, if we see demand for it.  We created this issue both to document the current situation and also so folks can comment if the normal default mechanism doesn't work well for them.  Please also note what you would prefer and why. The more well-supported requests we get, the more we can prioritize this issue.  We don't waste time implementing a feature that nobody seems to want.    And, at least for our [Nmap Security Scanner](https://nmap.org), the default timestamp methods seem to be working well enough for us.

**Comment by dmiller-nmap** [comment]
Since timestamp method selection is already available per capture handle, I'm closing this issue. The idea for getting a list of timestamp modes via ioctl is #17 

Regarding "TIMESTAMPMODE_QUERYSYSTEMTIME_PRECISE is probably what almost all, if not all, users would want," I think Nmap in particular would rather have all clocks monotonically increasing, since it's less important for us what time the wall clock said when a packet arrived as it is how long it has been since we sent the probe that elicited the response. Unfortunately, on all systems we use `gettimeofday()` for measuring time intervals, so QST is probably better for now, but nmap/nmap#180 may get fixed eventually :)
