### ISSUE TITLE
NpcapHelper.exe expired certificate for NPCAP 1.31

### ISSUE THREAD

**Issue by Bob-Fx** [nmap/npcap#501]
![expiredCert](https://user-images.githubusercontent.com/65665844/120700791-1610f480-c480-11eb-938f-77d1129453a2.PNG)
![expiredCert2](https://user-images.githubusercontent.com/65665844/120701210-8fa8e280-c480-11eb-90d8-5bc98cecd5d8.PNG)
from windows wireshark installations C:\Windows\System32\Npcap
File version 5.1.31.421
product version 1.31
file date 4/21/2021 4:46 PM

**Comment by dmiller-nmap** [comment]
The certificate used to sign the files expired, but that does not make the signature invalid. All files are countersigned by a timestamping authority, which authenticates that the certificate was valid at the time of signature. All file signature validation software should be able to correctly verify the files and timestamps, as Windows has done in your screenshots: "This digital signature is OK."

**Comment by Bob-Fx** [comment]
Great, thanks for the info!

Regards,

Bob Fenske
