### ISSUE TITLE
nmap strange behavior Windows (all versions)

### ISSUE THREAD

**Issue by telekomancer** [nmap/npcap#502]
Hi guys!

Recently i was trying to test some "basic" behavior on Windows (7, 8, 8.1, 10, Server 2008, Server 2012, Server 2016, Server 2019), no matter the patch levels or installed updates, the simple test is:

```
nmap localhost
```
 
When i see the output, i see some opened ports, and here is the weird thing:

If i apply Windows Firewall, for example to block port 445, from any to any, inbound and output and test again nmap, i still see the port open (if i go to a remote computer i see that the port is filtered but not from localhost).

So am trying to understand if this behavior comes from nmap, WFP, or some other thing affecting.

The steps to reproduce are pretty easy:

1.- Windows Machine
2.- Firewall Active on all profiles
3.- Pick an open port (for example 445, 137, 139, 3389, blah, blah)
4.- Apply a rule to all profiles with the desired behavior, lets say "Block from any to any the port 445)
5.- Scan from localhost to localhost and you'll see the port as "Open"
6.- Scan from localhost to the ip address that you have (for example, 192.168.1.2) and you'll see the port as "Open"
7.- Scan from ip address that you have (for example, 192.168.1.2) to  ip address that you have (for example, 192.168.1.2) and you'll see the port as "Open"
8.- Scan from a remote host (for example 192.168.1.3) to the desired machine (192.168.1.2) and you'll see the port as "Filtered"

Am searching for 4 days the answer to this behavior but i don't find a technical answer.

Kind regards!

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. Windows Firewall does not filter loopback traffic (network-layer traffic destined for the local Windows machine itself.) This is the same result you would get if you were using `iptables` on Linux and scanning your own system. To verify firewall behavior, the scan must be done from another system.

**Comment by telekomancer** [comment]
Thanks for the replay @dmiller-nmap , but Linux does it:

![imagen](https://user-images.githubusercontent.com/27900350/121082346-f5aca700-c7ab-11eb-94ef-dc4d1bfd8b92.png)

IPv6:

![imagen](https://user-images.githubusercontent.com/27900350/121082632-60f67900-c7ac-11eb-98f7-a1df99497d6a.png)

**Comment by telekomancer** [comment]
Hi @dmiller-nmap that's the final answer?

Kind regards

**Comment by dmiller-nmap** [comment]
@telekomancer Yes, this is a consequence of Windows' network stack design. It is not a flaw in Npcap. If you can demonstrate that the Windows Firewall prevents communication from an ordinary program (telnet, for example) but Nmap shows the port as open, then you should report that to Microsoft as a flaw in Windows Firewall.

**Comment by telekomancer** [comment]
Thanks for the answer.

Do you have any documentation related to that ?

Am just trying to understand that weird behaviour on Microsoft OS.
