### ISSUE TITLE
duplicate sent-out packets seen on local Interface 

### ISSUE THREAD

**Issue by yuanjianpeng** [nmap/npcap#51]
I have the same problem As: duplicate sent-out packets seen on local Interface nmap/nmap#1055
My OS is windows 10. there are two PC has this problem. 
When I uninstall antivirus program in one PC the problem solved. 
but another PC has no antivirus program. I don't know the reason.

**Comment by fyodor** [comment]
Hi all.  This issue hasn't had any updates in years and Npcap has changed quite a bit in that time.  If you are still experiencing any problems like then when using the latest version of Npcap (currently Version 1.60), please file a new bug with full details and we will be happy to take a look.
