### ISSUE TITLE
Npcap 1.40 Setup Failed to create the npcap service

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [nmap/npcap#513]
---------------------------
Npcap 1.40 Setup
---------------------------
Failed to create the npcap service: 0x00000000. Please try installing Npcap again, or use the latest official Npcap installer from https://nmap.org/npcap/
---------------------------
OK   
---------------------------
![Npcap 1.40 Setup](https://user-images.githubusercontent.com/46166740/122836276-78bc1a00-d2e1-11eb-84dd-32fe62401170.png)
![Npcap 1.40 Setup](https://user-images.githubusercontent.com/46166740/122836490-dd777480-d2e1-11eb-8645-1985885f1e07.png)

windows 21h1 19043.1052 x64

`npcap-1.40.exe /prior_driver=yes` fails to. Reinstalling npcap-1.31.exe works. after `npcap-1.40.exe /prior_driver=yes` deleted my npcap-1.31 driver. While npcap-1.31 works without any issues,  npcap-1.40 doesn't install.

**Comment by SilmorSenedlen** [comment]
Good day,
I have the same result on 3 hosts:
1. Windows 10 Enterprise LTSC / Version 1809 (OS build 17763.1935) x64 (AMD)
2. Windows 10 Enterprise LTSC / Version 1809 (OS build 17763.1999) x64 (Intel)
3. Windows Server 2019 / Version 1809 (OS build 17763.1879) x64 (VM) (Host system: VMware ESXi, 6.5.0 U3, 17477841) / VMware Tools 11.2.1.17243207
Logs from all 3 hosts:
[AMD_install.log](https://github.com/nmap/npcap/files/6689977/AMD_install.log)
[AMD_NPFInstall.log](https://github.com/nmap/npcap/files/6689978/AMD_NPFInstall.log)
[Intel_install.log](https://github.com/nmap/npcap/files/6689979/Intel_install.log)
[Intel_NPFInstall.log](https://github.com/nmap/npcap/files/6689980/Intel_NPFInstall.log)
[VM_install.log](https://github.com/nmap/npcap/files/6689981/VM_install.log)
[VM_NPFInstall.log](https://github.com/nmap/npcap/files/6689982/VM_NPFInstall.log)
Error when npcap service installing:
![npcap_install_error_01](https://user-images.githubusercontent.com/6761903/122840219-5c7ca500-d302-11eb-9a33-f63ad138eb34.png)
And also stucked on aborting:
![npcap_install_error_02](https://user-images.githubusercontent.com/6761903/122840215-5be40e80-d302-11eb-8ff7-e703dd636bc1.png)

On all hosts used local system admin account. But on VM, also new user with Administrators group rights was created, but with the same installation error result.

**Comment by gjf** [comment]
Hi there.

Same Problem, same error on Windows 10 x64 21H1:
![Безымянный](https://user-images.githubusercontent.com/322186/122843931-3ad2ec00-d309-11eb-8e52-0047762aba8b.png)

Npcap 1.31 installs OK. Have to revert back.

**Comment by fyodor** [comment]
Thanks everyone!  I'm able to reproduce this on one of my Windows 10 virtual machines too.  We're investigating the situation now.

**Comment by driver1998** [comment]
For the new comers that are affected by this issue, Npcap 1.31 is at https://nmap.org/npcap/dist/npcap-1.31.exe.
