### ISSUE TITLE
Move or remove Legacy loopback support option in Npcap installer

### ISSUE THREAD

**Issue by fyodor** [nmap/npcap#514]
With Npcap 1.50, the first of the installation options is "Legacy loopback support for Nmap 7.80 and only. NOT recommended."  It is disabled by default so you can't actually check it.  I think it's only enabled if you specify an option other than disabled to /loopback_support on the command line or if you have a previous version of Npcap installed with this option enabled.  If we're certain that it is hardly ever needed, we should probably make it a command-line-only option (and then potentially remove it entirely as the next later step).  Otherwise, we should probably move it to the bottom of the options list and allow users to select it.  Showing the checkbox but not allowing it to be selected might frustrate users.

**Comment by dmiller-nmap** [comment]
Beginning with Npcap 1.55, the legacy loopback checkbox and text field are hidden unless:
* the install is an upgrade and the previous installation used the option, OR
* the command-line `/loopback_support` option is used with a value other than "disabled" or "no"
