### ISSUE TITLE
npcap 1.50 fails to start service on Windows 7

### ISSUE THREAD

**Issue by gf-db** [nmap/npcap#517]
Steps to reproduce:
1. Install Windows 7 x64 SP1. I've encountered this problem on real hardware first and then verified it on a clean installation in the VM (Virtualbox 6.1 instance).
2. (required) Install SHA-2 driver signing update KB4474419-v3-x64 and reboot (https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=38222b3b-2bd2-4269-880d-35feddf42984)
3. (optional) Install the rest of updates. Did not seem to matter in my tests in a VM (tried installing npcap both before and after updates, the result was the same).
4. Install npcap 1.50 (either with default options or with Winpcap compatibility mode checkbox unchecked).
Results: 
Npcap installer reports success, but Wireshark cannot detect it.
"net start npcap" from elevated prompt responds with "System error 87 has occurred. The parameter is incorrect."
Observations:
The "Npcap Loopback Adapter" is not created by the installer. I can add it manually with "NPFInstall.exe -il": this creates the adapter, but "net start npcap" still reports the same error after this.
Relevant logs are in attachments:
[install.log](https://github.com/nmap/npcap/files/6773048/install.log)
[NPFInstall.log](https://github.com/nmap/npcap/files/6773049/NPFInstall.log)
[setupapi.app.log](https://github.com/nmap/npcap/files/6773050/setupapi.app.log)
[setupapi.dev.log](https://github.com/nmap/npcap/files/6773051/setupapi.dev.log)

**Comment by dmiller-nmap** [comment]
Thanks for this detailed report. There is nothing in the logs that seems to indicate a problem, so we will have to try to reproduce here and debug directly. In the meantime, have you tried checking the "Install older Npcap 1.31 driver" box? This may be an acceptable workaround until we can identify the problem directly.

As an aside, do you have a hard requirement for using Windows 7? Microsoft has stopped supporting it apart from Extended Security Updates which have to be purchased separately and will end in January 2023.

**Comment by dmiller-nmap** [comment]
We are working on this issue, with discussion under #536. Please follow there for updates, thanks.
