### ISSUE TITLE
NPCAP 0.996 No Network Access/No Valid IP?

### ISSUE THREAD

**Issue by ddubs13** [nmap/npcap#52]
I've googled this but can't find anything and what I can find is total greek to me, so I'm posting it here.

I installed this, and rebooted my machine, but it doesn't seem to be working? It's listed in my adapters as being enabled, but isn't in my active networks. It says there's no network access and when I attempted to troubleshoot, it said there was no valid IP configuration.

I have no idea what any of this means, if it's normal or how to fix it. Help?

**Comment by dmiller-nmap** [comment]
Closing this issue as stale. If Npcap 1.60 or newer exhibit the same problems, please open a new issue and include DiagReport output [as suggested in the Npcap Guide](https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-issues)
