### ISSUE TITLE
Can Npcap achieve a 10gbps traffic capture without packet lost?

### ISSUE THREAD

**Issue by LoveMyPillow** [nmap/npcap#528]
Assume that I have a very large RAM(64GB),  an advanced cpu, and the frame packet size is about 1024B. Can I achieve capture without packet lost in 10seconds(10gbps)? Is there any trick to do it?

**Comment by fyodor** [comment]
The issues tracker is not really for asking questions.  Maybe we should make an Npcap-specific mailing list or forum.  I just created an [Npcap Subreddit](https://www.reddit.com/r/npcap/) but there obviously aren't many users there yet.  I'm closing this "issue" but people are still welcome to add comments answering your question.
