### ISSUE TITLE
Does NPCAP still support 802.11 capture on Windows?

### ISSUE THREAD

**Issue by yujuiwu** [nmap/npcap#532]
I was using NPCAP 0.99r9 and it works fine (with ``PacketOpenAdapterNPF()`` modified). After upgrading to NPCAP 0.9983, Wireshark no longer captures anything over the WiFi adapter. 

I'm not sure, but seems it has something to do with this commit:
```
545c6778a6961ec56c54a0e7e7e9fbbfa80bc21e
Author:     Daniel Miller <dmiller@nmap.org>
AuthorDate: Thu Aug 8 15:12:40 2019 -0500
Commit:     Daniel Miller <dmiller@nmap.org>
CommitDate: Sun Aug 11 14:15:36 2019 -0500

Parent:     15765ba Unregister WFP callouts before destroying injection handles. See nmap/nmap#1678
Contained:  master
Follows:    v0.9982 (3)
Precedes:   v0.9983 (13)

New device structure

5 files changed, 99 insertions(+), 176 deletions(-)
Common/WpcapNames.h           |   8 +-
packetWin7/npf/npf/Openclos.c |  66 ++++++++++----
packetWin7/npf/npf/Packet.c   | 195 ++++++++++--------------------------------
packetWin7/npf/npf/Packet.h   |   4 +-
packetWin7/npf/npf/Write.c    |   2 +-
```

Also, when NPCAP 0.9983 is used, I can't see the symbolic links created in ``DriverEntry()``.

Can someone give me some clue on how I can get it capture again?

Thanks!

**Comment by dmiller-nmap** [comment]
This is a known issue in Npcap 0.9983 to Npcap 1.20. Beginning with Npcap 1.30, functionality has been restored and improved.

**Comment by yujuiwu** [comment]
That really helps, thank you so much!
