### ISSUE TITLE
Silent install with winpcap_mode=yes does not work as expected

### ISSUE THREAD

**Issue by aancag** [nmap/npcap#545]
I try to install Npcap OEM 1.55 by using the silent installer option as in the example below (I also have installed locally  WinPcap 4.1.3):

`C:\WINDOWS\system32>C:\Users\aga\Downloads\Npcap\npcap-driver-oem.exe /require_features /winpcap_mode=yes /S`

According to the documentation, winpcap should be uninstalled when providing the `/winpcap_mode=yes` option. 

When running the GUI version of the Npcap OEM for installing, having the option "Install Npcap in Winpcap API-compatible Mode" checked, Winpcap 4.1.3 gets uninstalled (at least after performing a clean installation).

When running the silent install, the install.log file shows the following error:
```
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\aga\AppData\Local\Temp\nsj8EB1.tmp\nsExec.dll"
File: skipped: "C:\Users\aga\AppData\Local\Temp\nsj8EB1.tmp\nsExec.dll" (overwriteflag=1)
DetailPrint: Error executing "C:\Program Files\WinPcap\uninstall.exe": 2
SetFlag: 2=1
Jump: 1189
```

But when running the GUI version, the install.log file shows that it succeeds in removing the winpcap files, and it also manages to uninstall the winpcap.
```
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\aga\AppData\Local\Temp\nsbF0B1.tmp\nsExec.dll"
File: skipped: "C:\Users\aga\AppData\Local\Temp\nsbF0B1.tmp\nsExec.dll" (overwriteflag=1)
Delete: "C:\Program Files\WinPcap\uninstall.exe"
Delete: DeleteFile("C:\Program Files\WinPcap\uninstall.exe")
RMDir: "C:\Program Files\WinPcap"
RMDir: RemoveDirectory("C:\Program Files\WinPcap\")
SetFlag: 2=0
Call: 1111
```

I've tried the silent install also only with the winpcap_mode option:
`C:\WINDOWS\system32>C:\Users\aga\Downloads\Npcap\npcap-driver-oem.exe /S /winpcap_mode=yes` but it doesn't work either.
 

Note: I tried to install Winpcap either from command line or from GUI, same result

OS: Windows 10 Enterprise

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. Looking at our installer code, it appears that we may not be correctly handling the return value of the WinPcap uninstaller. However, the result of this would be that we never treat an uninstaller failure as a reason to fail the installation. Rather, we press on with overwriting any existing WinPcap files. Can you please provide some more information so we can diagnose the issue?

1. Does Npcap fail to install in this case? Npcap installer return code, presence of Npcap installation directory, etc. would be helpful.
2. Is WinPcap still present on the system? Is it removed following a reboot of the system?
3. Is there any software on the system that may be currently using WinPcap when the Npcap installer runs?

**Comment by aancag** [comment]
Hi,

1. No, Npcap succeeds in installing every time, but the issue is that Winpcap does not get uninstalled when using the silent install.
2. Yes, Winpcap is still present on the system, and after performing a reboot of the system it is still present.
3. No, I did the test just to see if winpcap gets uninstalled when installing npcap. There is no aplication using winpcap when performing this test.

I did the following test:
- Install winpcap silently by using the follwing command:
`C:\Users\aga\Downloads\Npcap>winpcap-nmap-4.13.exe /S`
The application is installed in the `C:\Program Files\WinPcap` path. The return code is 0. (echo %ERRORLEVEL%)
- Ran silent npcap install  with the following  command:
- `C:\WINDOWS\system32>C:\Users\aga\Downloads\Npcap\npcap-driver-oem.exe /require_features /winpcap_mode=yes /S`. The npcap application is installed in the following path: `C:\Program Files\Npcap`. The return code here is 0 too. Npcap is successfully installed, but the `C:\Program Files\WinPcap` directory is still present and the winpcap aplication still installed.

I've attached the Npcap [install.log](https://github.com/nmap/npcap/files/7242830/install.log) file too. If additional information is required and I haven't mentioned it please let me know.

**Comment by dmiller-nmap** [comment]
It appears that the WinPcap uninstaller encountered an error, but we do not have a log of what that error might have been. We have recently made several improvements to our installer, one of which is to conduct a manual removal of WinPcap without invoking the WinPcap uninstaller itself. In this way, we will be able to log any errors. Additionally, we do not consider any errors in this removal to be a barrier to correctly installing Npcap, so the installer will continue without problems in that case. If you want to provide further info, the output of [DiagReport](https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-issues-diagreport) ought to show what remnants of WinPcap have been left behind. However, we do not consider that these will present any problem for an application to correctly use Npcap.

I will close out this issue when the next Npcap release is made with these installer improvements.

**Comment by aancag** [comment]
Indeed, there is not an error uninstalling winpcap on npcap installation, but it has a different behavior when running the installer from GUI (sometimes it manages to uninstall winpcap) and when running the silent install. In any scenario the npcap is successfully installed.

I've made the test again and attached the diag report too: [DiagReport-20211014-204813.txt](https://github.com/nmap/npcap/files/7348239/DiagReport-20211014-204813.txt)

**Comment by dmiller-nmap** [comment]
Thanks again for reporting this. The new Npcap 1.60 installer performs the uninstallation of WinPcap on its own in both silent and GUI mode, instead of invoking the WinPcap uninstaller. This allows us to have better insight if anything should go wrong, as well as to clean up partial WinPcap installs that may have been left from previous failures. This should resolve the issue you were seeing. Since this code has been entirely rewritten, please report any problems as a new issue.
