### ISSUE TITLE
wireshark alert

### ISSUE THREAD

**Issue by LoveLy2021** [nmap/npcap#554]
<img width="605" alt="Screenshot 2021-10-22 062708" src="https://user-images.githubusercontent.com/92986180/138447766-e557220f-26bc-4d27-b815-3a4e27f19844.png">

**Comment by dmiller-nmap** [comment]
This is a known issue: NDIS stack maintenance operations may interrupt captures in a way that is indistinguishable from the adapter being unplugged. Npcap 1.60 introduces a change (#506) that will allow user programs like Wireshark to keep capturing if the adapter comes back, but it will take some time before Wireshark developers can change their code to take advantage of it.

@geraldcombs - is there anything we can do to help Wireshark in this situation?
