### ISSUE TITLE
npcap 1.55 bugs : “enforced” option in command-line installer doesn't work.

### ISSUE THREAD

**Issue by qiwk** [nmap/npcap#556]
When trying to install npcap from command line, when I use the "enforced" option(for: /admin_only、   /dot11_support、  and /winpcap_mode), it doesn't do anything. When the installer runs the check boxes are unchecked.  But all the other options "disabled", "yes" and "no" all work fine.

Npcap 0.9984  says "Fixed processing of the "enforced" value for several command-line installer options. Fixes #1719.(http://issues.nmap.org/1719)"
But the same issue still exists in npcap 1.55.

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. I can confirm this issue and will make sure we get this addressed in the next release.

**Comment by dmiller-nmap** [comment]
Npcap 1.60 installer contains this fix.
