### ISSUE TITLE
Outbound packets sent but not captured, or duplicated

### ISSUE THREAD

**Issue by uecasm** [nmap/npcap#56]
## Problem

When using Wireshark, inbound packets are displayed but outbound packets are not displayed.

## Environment

* Windows 8.1.1 x64
* Wireshark 3.0.1 (also tested with 2.x)
* Npcap 0.995

## Details

An application is using the WinPcap 4.1.3 SDK to send and receive raw ethernet frames.

With WinPcap 4.1.3 actually installed, this works as expected (all packets are sent and received correctly, and using Wireshark on the interface sending the packets shows both the inbound and outbound packets).

With Npcap 0.995 installed (in WinPcap compatible mode), the packets are sent and received correctly but Wireshark (on the sending interface) only shows the inbound packets, not the outbound packets.

The Wireshark configuration is the same between these two cases; the only change is to uninstall one capture library and install the other.

Possibly of note (but probably unrelated) is that with Npcap installed the network interface shows bindings to NPF and NPCAP, but with WinPcap installed these do not appear.  Unticking these causes Wireshark to not capture anything at all.

**Comment by fyodor** [comment]
Hi all.  This issue hasn't had any updates in years and Npcap has changed quite a bit in that time.  If you are still experiencing any problems like then when using the latest version of Npcap (currently Version 1.60), please file a new bug with full details and we will be happy to take a look.
