### ISSUE TITLE
VPN packets not "working" when capturing VPN interface with npcap (by Wireshark)

### ISSUE THREAD

**Issue by AndNovAtor** [nmap/npcap#560]
I saw a lot of simmilar issues here, some for old version. But I still have problem on 1.31 version.

I have PPTP and L2TP/IPSEC VPNs configured on my Winddws 10 PC. All works normal.
When I connected to any VPN (for example, MIAC_l2tp [L2TP/IPSEC]), when I starts capture packets on this connection (on my PC, it shows as "Подключение по локальной сети* 11)"), VPN connection stops working. No ping to any "private network" IP, all tcp packets are "timeout". Wireshark (for example) shows some captured packages for this connection, but most of all are faled.
When I stop capturing, all AGAIN become work NORMAL (packets "works" in VPN connection, all ping to "private network" works),
So, I CAN'T REALY capture any packets on VPN connection.

First time I detected it was near 0.9996 version, but I think that it was earlier.

Some screenshots:
![изображение](https://user-images.githubusercontent.com/3628514/140622624-877a0d7b-64d5-455e-a329-6fa3bc7560a6.png)
![изображение](https://user-images.githubusercontent.com/3628514/140622652-ab9b7a3c-a97a-4bd6-93a3-b157f715d17c.png)
![изображение](https://user-images.githubusercontent.com/3628514/140622761-a53dcde3-cd85-4523-a6ed-65e03b2eab2a.png)

Start capturing...
![изображение](https://user-images.githubusercontent.com/3628514/140622696-edef94f9-0d0c-47a2-b961-8c651bc93fa5.png)
![изображение](https://user-images.githubusercontent.com/3628514/140622707-827d6d70-61ca-43fc-9271-c348175c5acb.png)
![изображение](https://user-images.githubusercontent.com/3628514/140622711-1b21cf63-3d9e-41a1-804c-fb7c710995b0.png)

... Stop capturing
![изображение](https://user-images.githubusercontent.com/3628514/140622712-01b7cb5e-7b44-47c1-b9b5-d80edde3fc39.png)
![изображение](https://user-images.githubusercontent.com/3628514/140622720-c6150f1c-600e-40d5-b031-7c248e601f41.png)

**Comment by jossas** [comment]
Same issue here.. Any response?

**Comment by HXCK3D** [comment]
Same issue with Wireshark Version 3.6.1 (v3.6.1-0-ga0a473c7c1ba) and Npcap 1.55 on Windows 10 Pro 21H1 (build ver. 19043.1469)

**Comment by vargasol** [comment]
I have the same issue with Wireshark version 3.6.2 and Npcap 1.6.

**Comment by dmiller-nmap** [comment]
Thanks everyone for reporting this. Does the issue still happen if you do not use promiscuous mode? 
![image](https://user-images.githubusercontent.com/10443029/160463450-722a8ef6-7be9-4717-a1ec-1329278f86dc.png)

**Comment by AndNovAtor** [comment]
> Does the issue still happen if you do not use promiscuous mode?
@dmiller-nmap , Confirm, that not (workaround? intended?).
Enabled VPN, working. Than changed options to disabled `Смешанный` / `Promiscuous` mode:

![image](https://user-images.githubusercontent.com/3628514/160467703-1d81645e-c292-4ff6-bbdd-ba4307dcc72a.png)

Than start capture - all good (active VNC connection with "test" ping)!
![image](https://user-images.githubusercontent.com/3628514/160468200-85c0f7ed-4d49-480d-9c63-0b020eb92148.png)

**Comment by TheseGoTo11** [comment]
I also cannot capture any traffic on my VPN's virtual Enternet interface. Makes no difference whether promiscuous is on or off.

I can see the VPN traffic flowing on the non-virtual wifi interface, but that traffic is encrypted.

WireShark 3.6.3, npcap 1.6, Windows 11 Home 21H2, build 22000.593

**Comment by AndNovAtor** [comment]
> I can see the VPN traffic flowing on the non-virtual wifi interface, but that traffic is encrypted.

@TheseGoTo11,  You open wrong issue page. Please see another (simmilar) issues for your problem. This issue about "another" problem, completely not working VPN

**Comment by TheseGoTo11** [comment]
Ah, yes I see. My VPN traffic still flows, unlike the other commenters. I just can't capture it. I will look for an answer elsewhere. Thanks.

**Comment by fyodor** [comment]
Hi folks!  Is anyone able to test with the new [Npcap Version 1.70](https://npcap.com)?  We didn't find a confirmed fix, but we made [so many changes and fixes to related code](https://npcap.com/changelog) that there is a chance it is resolved.  We'd love to know either way.  I'm keeping this issue open for now.

**Comment by AndNovAtor** [comment]
> so many changes
You don't believe @fyodor , but... I "CAN'T" reproduce this with Npcap 1.70! Even with enabled "promiscuous mode"

**Comment by AndNovAtor** [comment]
@fyodor , with some _old_ Npcap and "promiscuous mode" ON with VPN - vpn packets stop working:
 
![image](https://user-images.githubusercontent.com/3628514/176267361-7b094341-2ff1-4f92-8e0a-ebe61b596828.png)
![image](https://user-images.githubusercontent.com/3628514/176267515-bd6c0914-c824-4096-85e2-956ee5c4288a.png)

Then, installed Npcap 1.70 (no reboot), again, "promiscuous mode" is ON... And VPN works!

![image](https://user-images.githubusercontent.com/3628514/176268086-38db834d-73e3-41ad-9a16-9231cf4636b0.png)

![image](https://user-images.githubusercontent.com/3628514/176268205-93d15162-27c8-4670-b29d-fc71cba544ac.png)

**Comment by fyodor** [comment]
@AndNovAtor - That's great news!  I'll close this issue as fixed.  If anyone is still having VPN-related problems with 1.70, it might be best to create a new issue to avoid confusion.
