### ISSUE TITLE
Capture Beacons on 2.4G and 5G WiFi channels

### ISSUE THREAD

**Issue by CrimpOn** [nmap/npcap#561]
I want to collect management frames from my mesh WiFi system to investigate some timing issues using Wireshark on Windows 10. (One router and two satellites: a total of six MAC addresses). Have a pair of Panda PAU09 dual band WiFi adapters that support monitor mode. Have a capture filter of: "ether src (MAC1 or MAC2 or ... MAC6)" (with actual MAC addresses) on each adapter, Checked Promiscuous Mode and Monitor Mode. 

Running Wlanhelper 1.31 (installed by Wireshark) as Administrator, I set one PAU09 to channel 8 and the other to channel 48. When Wireshark runs, it captures Beacon frames from all three access points on 2.4G, but does not capture the 5G Beacon frames.  I notice that setting channel 48 reports 'success', but when I check later, Wlanhelper reports the adapter on channel 36.  (I know the channel is actually 36 through 48, so am not sure how to interpret this.)

Any ideas what I have done incorrectly?

**Comment by dmiller-nmap** [comment]
Wlanhelper doesn't offer all configuration options in interactive mode. Run `WlanHelper.exe -h` to see a more complete usage summary. Check whether you need to modify the modulation ([OID_DOT11_CURRENT_PHY_ID](https://docs.microsoft.com/en-us/previous-versions/windows/hardware/wireless/oid-dot11-current-phy-id), e.g. `WlanHelper.exe modu ofdm`) or frequency ([OID_DOT11_CURRENT_FREQUENCY](https://docs.microsoft.com/en-us/previous-versions/windows/hardware/wireless/oid-dot11-current-frequency), e.g. `WlanHelper.exe freq 32`). Different modulations require different OID requests to set the "channel," and OFDM (802.11a) requires you to set the channel with `freq`. Not all modulations and OID requests are supported with WlanHelper, but any tool that would allow you to make these configuration changes will work with Npcap.
