### ISSUE TITLE
Npcap Bug Report

### ISSUE THREAD

**Issue by schabertrobbinger** [nmap/npcap#562]
Hello,

I recently tried to run Nmap on a Windows 7 Ultimate virtual machine up on a virtual network. Installation appears to have gone through flawlessly (just downloaded from official site, next, next, and next), but I see the error message:

root@WIN7-CU C:\Program Files (x86)\Nmap>nmap -sS -T1 -p 4333 -Pn -oN log_1.txt
198.41.0.4
Starting Nmap 7.92 ( https://nmap.org ) at 2021-11-18 13:49 Eastern Standard Tim
e
mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled.
Try using --system-dns or specify valid servers with --dns-servers
dnet: Failed to open device eth3
QUITTING!

at run time while trying to scan a virtual IP on my virtual network I can ping. I think that I have pretty much reached the limit of my technical knowledge at this point, so I am hoping that somebody on the dev side will be able to help me out. First, I was puzzled that I had to include the -n flag to get rid of the mass_dns error because I didn't need to do that on a virtual Ubuntu box running alongside on the same virtual subnet. What was more puzzling to me (and remains so) was the dnet error; to investigate a bit, I went ahead and ran the DiagReport.bat script but noticed the suspicious-looking error message:

Get-NetAdapterBinding : The term 'Get-NetAdapterBinding' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

in the output. A cursory Google suggested to me that NetAdapter cmdlets were only introduced in Windows 8, so I started to wonder if there could be some sort of versioning error in the mix. In a nutshell, I am a novice Nmap user keen to get operational under Windows 7. While I am of course interested in improving the software overall, I would be very happy to try out an older version of the software which ought to work more reliably out of the box on a legacy machine if that would get me operational faster.
[DiagReport-20211119-102851.txt](https://github.com/nmap/npcap/files/7572480/DiagReport-20211119-102851.txt)

**Comment by code8102** [comment]
Hello,
i have the same problem since i installed the lastest nmap/npcap.

**Comment by schabertrobbinger** [comment]
If it helps, I tried an old Nmap 6.01 just now and it worked as expected with no errors. This was the case even if I ran without the -n flag.

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. This is a known issue (#536) with Npcap 1.50 and 1.55: attempting to allocate from NonPagedPoolNx on Windows 7 fails, causing the driver to fail to start. This will be resolved in the next release. Note that Windows 7 has been out of mainstream support for 11 months. We intend to continue to support it until the end of Extended support in 2023, but Windows 10 and newer will have better performance and compatibility.
