### ISSUE TITLE
Installer drops wrong npcap.sys

### ISSUE THREAD

**Issue by ka1ias** [nmap/npcap#564]
Running win10 ent 21H2 x64.
Tried to install npcap version 1.31, 1,50, v 1.55 - all same issue.
For some reason (e.g the 1.55) the installer drops 0c152ef5f6ccfa1d6b26a5d3e07597528aae121d *npcap.sys
instead of f242a5fee81346a026c8ea5a8e92376866d3a9b9 *npcap.sys
The former is not digitally countersigned by MS and as such it will not load.
Manually extracting the correct file and replacing in drivers folder does solve the problem.

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. Can you provide a copy of install.log from the Npcap installation directory? NPFInstall.log would also be helpful.

**Comment by ka1ias** [comment]
Hi, the same issue with 1.60 on this particular machine.

14eeb58e55afbf12d48e24f0372bc8984aeb0d54 *npcap.sys
instead of 
08070f574378a0512c66a757301936959841e2e3 *npcap.sys

According to the log its a win7 machine, which is clearly not.
DetailPrint: Windows CurrentVersion: 6.1 (Win7)

Since I know how to address the problem (likely one-off in my case), I suggest to close the issue.

[install.log](https://github.com/nmap/npcap/files/8067564/install.log)
[NPFInstall.log](https://github.com/nmap/npcap/files/8067565/NPFInstall.log)

**Comment by ka1ias** [comment]
Problem solved:
I'm using the FAR manager. When I compared the environment variables of a plain cmd shell and the one via FAR, the difference is
__COMPAT_LAYER=Win7RTM
and that seems to cause the windows version confusion. Running the installer directly from cmd installs the correct version of the driver.

**Comment by fyodor** [comment]
Thanks for the update, @ka1ias .  It sounds like Npcap was following the __COMPAT_LAYER directive and installed as if it was the requested "Win7RTM".  We could potentially override this in the installer by unsetting the variable, but it is possible that some people might set it on purpose and expect it to be honored.  So I think we'll hold off on doing anything for the moment and leave the issue closed, but anyone with comments about what they think we should do with this variable is welcome to leave them here anyway.
