### ISSUE TITLE
1.60: EULA / Copyright typos 

### ISSUE THREAD

**Issue by bubbasnmp** [nmap/npcap#566]
Version 1.60  
  
"relicence"  
Should it be "relicense"?  
  
"governed by the laws the United States"  
Should it be "laws of the" ?
  
Near the end:  
"modify itâ€™s software"  
  
![211212_eula_typos](https://user-images.githubusercontent.com/17128740/145723595-267d0735-13b9-492e-9ea3-05811daeea47.png)

**Comment by fyodor** [comment]
Thanks, fixed.
