### ISSUE TITLE
Add ARM64 Win10 Support to Npcap

### ISSUE THREAD

**Issue by fyodor** [nmap/npcap#57]
We are considering adding Windows 10 ARM64 support to Npcap.  With that, we would support all 3 Windows 10 architectures.  Windows 10 ARM64 is a new (released in late 2017) system that is used on some more portable laptop/tablet devices like the Samsung Galaxy Book 2.  @pmsjt from Microsoft has already done and tested an initial port and submitted it as a pull request here: https://github.com/nmap/npcap/pull/18 .
Having ARM64 Npcap should enable Nmap to work on these ARM64 devices too, which would be nice.

We're wondering how much Nmap/Npcap user interest there is in supporting Windows 10 ARM64?  If it is something you want for a specific reason, please comment and describe your use case, including any particular devices you'd want to make sure are supported.  Based on the responses, we'll decide whether to buy some ARM64 hardware and get to work.  Thanks!

**Comment by opsmgr3774** [comment]
+1 looking to get this up and running for a very mobile NetSec/diagnostic Surface Pro X setup.

**Comment by hmartinez82** [comment]
+1

**Comment by guyharris** [comment]
> Dear @pmsjt and @fyodor
> 
> I tested on the Samsung Galaxy Book2(Cellular version) using the privately built files of @pmsjt .
> 
> a) Ethernet, Wi-Fi ==> Working well
> b) Cellular ==> Link-layer Header is unknown
> 
> I think that Qualcomm Mobile Broadband Device driver uses the Raw IP.
> Please check the cellular issue.

That's nmap/nmap#1573, which is not ARM-specific, and has been resolved.in 39eb0a04c41e94e1a62918f79baffbddeec2759a; that fix first appeared in 0.9990.

**Comment by fyodor** [comment]
I am just adding a couple of notes from the duplicate issue #273 .  First of all, the error you apparently get when installing is "Failed to create the npcap service: 0x800f0203".  That might be helpful for people Googling the issue.  Second, I wanted to note @guyharris suggestion that we could make the installer fail on ARM with a clear error message until we're able to add full support.  We do still want to add that support, but we have some higher priorities at the moment.

**Comment by fyodor** [comment]
I just wanted to note that another Npcap customer requested ARM64 support today.  So there is definitely demand.

**Comment by jeffeharris** [comment]
Another request for npcap on ARM64 for my Surface Pro X.

I take it there are no known workarounds?

**Comment by pmsjt** [comment]
There is. Compile the driver from my fork.

https://github.com/pmsjt/npcap

**Comment by fyodor** [comment]
For prioritization purposes I wanted to note that we received another customer request for this today.  We are bumping up the priority in our roadmap.

**Comment by dmiller-nmap** [comment]
Npcap 1.40 can be installed on Windows 10 for ARM64.
