### ISSUE TITLE
Mini-redesign of Npcap.com website

### ISSUE THREAD

**Issue by fyodor** [nmap/npcap#576]
As part of branching the Npcap content off from nmap.org/npcap into its own npcap.com website, we are considering doing a fairly simple/fast redesign to address some long-running deficiencies in our existing templates.  Key goals:
* Make it more mobile friendly--probably by changing the sidebar into a top-menu type of organization
* We will probably get rid of the "advertising space" as part of this since we don't particularly like having Google banners and we are currently able to support the project through Nmap OEM and Npcap OEM licensing anyway.
* We will probably need a simple site logo.  While in the future we will probably use a logo design site/contest to create a new one for Npcap, for now we'll probably do "Nmap Eye with site URL below it" or similar like we do with all the other sites.

The goal would be to hopefully port this to the other sites in the future for consistency and so they can benefit from these same improvements.  We will probably add separate issues once this one is finished for doing the porting.

**Comment by guyharris** [comment]
> As part of branching the Npcap content off from nmap.org/npcap into its own npcap.com website

Moving the content to npcap.com appears already to have been done; should libpcap and tcpdump switch to downloading from npcap.com in its CI setup, and use npcap.com in any documentation we write for building tcpdump on Windows, and should Wireshark use npcap.com in messages, installers, and documentation referring to the Npcap site?

**Comment by fyodor** [comment]
Yeah, @guyharris , that would be great!  We will soon be rewriting of our links from nmap.org/npcap/* to npcap.com/* as well.  Both old and new sites are working right now (from exactly the same document tree), but we will soon put HTTP redirects in place to npcap.com so it is clearly the canonical site without breaking old links from elsewhere. The new URL makes all Npcap links shorter, and also reinforce that Npcap is a 1st-class project in its own right.  It's used by hundreds of popular software programs these days and isn't "just an Nmap thing".  Being smaller than most of our other web sites also allows us to more easily experiment with improvements like the site mini-redesign before tackling them for much larger sites like nmap.org and seclists.org.

**Comment by guyharris** [comment]
OK, I've updated stuff in libpcap and tcpdump, and Gerald's updated stuff in Wireshark.

Speaking of the Npcap site, there's a "User's Guide" link in the sidebar, which links to a document with multiple sections, one of which is called "Npcap User's Guide".  The Introduction begins with

> This Manual describes the programming interface and the source code of Npcap. It provides detailed descriptions of the functions and structures exported to programmers, along with complete documentation of the Npcap internals. Several tutorials and examples are provided as well.

but the Npcap User's Guide section covers things such as installation and bug reporting that are of interest to users who installed it for use by precompiled software, so that section isn't developer-only.  Perhaps the document should be called the "Npcap Manual" or something such as that, and the first paragraph in the Introduction expanded.

**Comment by fyodor** [comment]
Hi @guyharris.  Good point!  I'm closing this issue itself since the redesign it's talking about is done, but we agree that the Guide could use some improvements/rewriting/reorganization too.  It was sort of cobbled together from our marketing copy and the old WinPcap guide and is a great resource, but could use more work too.
