### ISSUE TITLE
Npcap 1.60 installer/uninstaller freeze

### ISSUE THREAD

**Issue by fyodor** [nmap/npcap#577]
We received a report from a licensee that the Npcap uninstaller was freezing (which also caused the installer to freeze) when they ran in silent mode.  Interestingly, it only seemed to happen on systems which had pending Windows changes for which a Windows reboot was required (but hadn't been done yet).  After a reboot it worked fine.  Windows was refusing to stop the driver because it thought a process was still using the driver, but the uninstaller was unable to find any such process.  We have put in a workaround for the next release which will give up after 10 seconds of trying to unload the driver if there is no output.  This seems better than freezing forever waiting on an event which is unlikely to ever happen.   Even though we have a planned workaround, we're adding this issue to provide more background and in case anyone else has experienced the problem and has comments/info.  We've only had this report from one customer who I think received it from their customer.

**Comment by fyodor** [comment]
Note: In prep for next release, @dmiller-nmap  is double-checking the change he made to extend the timeout and also making sure he didn't remove it for this particular command.

**Comment by fyodor** [comment]
I'm closing this since we have the workaround and there isn't much more we can do unless there is a way to reproduce the problem.  If anyone is still experiencing this, please leave a comment and we can re-open.

**Comment by evantkraus6** [comment]
I am noticing this behavior when attempting to uninstall Npcap 1.60 silently in a script. Npcap 1.60 was installed via the Wireshark 3.6.7 installer. Rebooting the system, unfortunately, did not lead to a different result.  I upgraded to Npcap 1.70 independent of Wireshark and see the same thing, where the silent uninstall is unresponsive.
