### ISSUE TITLE
Npcap 0.992 - Duplicate packets

### ISSUE THREAD

**Issue by R-Smith** [nmap/npcap#58]
I'm seeing a similar problem seen in the closed issue nmap/nmap#1055.

Basically I'm seeing duplicated outbound packets in Wireshark with Npcap.  I do not see the issue when using WinPcap.  The person who posted issue nmap/nmap#1055 said that toggling the Npcap driver on the network adapter would temporarily fix the issue, however, this does not seem to work for me.  When viewing in Wireshark, the timestamps of the duplicated packets are a few nanoseconds apart.  The receiving end does not see the duplicate packets, so it's not actually transmitting them.  I've seen the issue on multiple machines and Npcap versions, but my current setup is:

Npcap 0.992
Windows 10 1809
Wireshark 3.0.1

**Comment by kjczarne** [comment]
Any news on this one? Experiencing exactly the same issue.

**Comment by suazhero** [comment]
Hello, same issue on version 1.0.0. 
Didn't have time to test but are packets actually sent twice or just maked duplicated on wireshark?
Thx

**Comment by guyharris** [comment]
> Didn't have time to test but are packets actually sent twice or just maked duplicated on wireshark?

Wireshark just displays what it was handed by libpcap/WinPcap/Npcap/etc.; the packets Npcap passes on are the packets that are delivered to its driver in the networking stack.  If they're duplicates, rather than being sent twice, perhaps NDIS is delivering the same packet twice to the Npcap driver.

**Comment by jimmyroy67** [comment]
I am currently seeing this duplicated activity using wire-shark  3.4.3 and Npcap 1.10.  Has there been further discussion or possible causes of the duplicate packets.  i am seeing these from the source address both UDP and SNMP

**Comment by bhilgenkamp** [comment]
I've had this issue on any 3.x version of Wireshark when using npcap driver. Really hoping there will be a fix for this as it's basically useless when there are so many duplicate packets in every capture.

**Comment by matman13** [comment]
See dmiller-nmap's comment here for a possible explanantion.

https://github.com/nmap/npcap/issues/285

**Comment by dmiller-nmap** [comment]
This is a known complication when WinPcap is installed as well as Npcap. Discussion at #285.

**Comment by finert** [comment]
I am still having this issue for almost 2yrs now - on all three workstations from NPCAP 0.9xx to current 1.60

All machines have WMWare Workstation installed, none of them is having WINPCAP installed in parellel, on one it WAS installed if that helps...

Seeing every sent packet twice still sucks - any clues where this might come from and how to fix it?

**Comment by fyodor** [comment]
Thanks for the update here and on #285, @finert.  Since #285 seems to be the same issue and we already have it on our high priority bug list, I'll leave this one closed.  Cheers!
