### ISSUE TITLE
npcap 0.992 prevents PPPoE from working

### ISSUE THREAD

**Issue by bitbanditorg** [nmap/npcap#59]
We have many Windows 7 installs and all of them have problems connecting with PPPoE when npcap is installed. I have tried 0.99-r7 and 0.992 version but the symptom is the same. If I uninstall the npcap and install winpcap 4.1.3 the problem disappears.

After installing npcap and trying to make a PPPoE connection an error window pops up with RAS error code 692: ERROR_PORT_OR_DEVICE, A hardware failure has occurred in the port or attached device. The second try shows a different RAS error code 813: ERROR_BROADBAND_ACTIVE, You have attempted to establish a second broadband connection while a previous broadband connection is already established using the same device or port. All other tries give the same error code 813.

Disabling npcap on the ethernet interface under the PPPoE connection doesn't help. Stopping the npcap service does not help either. Another phenomena is something prevents Windows to be restarted, it stucks on the rebooting screen forever after the RAS error. Even the npcap uninstall stucks at 90% and never finishes after trying to use PPPoE. The uninstall log shows no problem, the last line is "Delete file: C:\Program Files\Npcap\FixInstall.bat". After restarting the computer the install.log contains more lines after this point. The last line shows "Jump: 76" and the service has removed.

The PPPoE connection should be established by the help of RAS. The computer is connected to a HGW with a 1 Gbps ethernet interface. The broadband connection is created in the Network Sharing Center:
* Set up a new connection
* Connect to the Internet
* Set up a new connection: WAN Miniport (PPPoE)
* Broadband (PPPoE)
* Enter username and password

I tried installing npcap with many different options, but none of them help:
* With or without WinPcap compatibility mode
* With or without Support loopback traffic

**Comment by CameronD73** [comment]
This is just to confirm the bug is still present in V1.0 of npcap, Win 7 x64.  Exactly as described in the  original post.

In my case the bug is not critical to anything - I was just using that laptop as a potentially sacrificial system for diagnostics as requested by my ISP. I was not ready to expose a newer PC directly to the internet.

**Comment by fyodor** [comment]
Thanks for the update.  Given that Microsoft [completedly ended Windows 7 support](https://www.microsoft.com/en-us/microsoft-365/windows/end-of-windows-7-support) in January 2020 and isn't even making security fixes any more, we have also ceased actively supporting Windows 7.  If someone is able to debug this and finds a good solution and submits a pull request, we would consider integrating that.  So I am closing this issue for now, but folks can still make comments and it could still be re-opened if things change.  Cheers.
