### ISSUE TITLE
Investigate simpler driver install functions

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/npcap#595]
Reference: https://docs.microsoft.com/en-us/windows-hardware/drivers/install/functions-that-simplify-driver-installation

Remaining unknown: can we use these for a NDIS LWF? What about the NetCfg API functions?

**Comment by fyodor** [comment]
After further investigation, @dmiller-nmap reports that these might not be useful to us: "Those are PnP driver functions, so it relies on having a device on the system that the driver matches. Npcap creates its own "device" when it runs, so it has to use a different driver install API."
