### ISSUE TITLE
npcap freezes when used from windows service

### ISSUE THREAD

**Issue by pquiring** [nmap/npcap#596]
My new app works great when using npcap from command line but when the app tries to use npcap from a windows service some function calls freeze (either pcap_compile() or pcap_sendpacket() freeze).
I thought maybe it's a user context error.  The service normally runs under local SYSTEM account.  Also tried a generic user account.  Same problem.
Any idea why?
Thanks,

**Comment by pquiring** [comment]
Never mind, think I found the issue in my code.

Thanks,

**Comment by odinsphere87** [comment]
How did you solve the problem?
