### ISSUE TITLE
npcap uninstall fails with wlanhelper in interactive mode

### ISSUE THREAD

**Issue by packetfoo** [nmap/npcap#60]
This is just a minor thing - if npcap is reinstalled it de-installs the previous version. This fails if wlanhelper.exe is still running in interactive mode, for obvious reasons. Maybe a check could be added to see if wlanhelper is still running and prompting for a close, just like it does for wireshark.exe?

**Comment by dmiller-nmap** [comment]
Npcap's installer and uninstaller now properly check for processes which are using Npcap resources (DLLs and driver handles). These changes and all related bugfixes have been final since Npcap 1.20.
