### ISSUE TITLE
any npcap commands to test the npcap loopback? it's not working in wireshark, maybe an npcap issue

### ISSUE THREAD

**Issue by gartha1** [nmap/npcap#604]
Are there any npcap commands to test the npcap loopback? it's not working in wireshark, maybe an npcap issue

**Comment by guyharris** [comment]
"Not working" in what sense?

Does it not show up in Wireshark?

Or does it show up, but gives an error if you try to capture on it?  If so, what error?

Or does it show up, not give an error, but also not show any packets, even if you do `ping 127.0.0.1` in a Command Prompt, PowerShell, etc. window?

Or does it show packets, but Wireshark doesn't dissect them correctly?

Or some other issue?

**Comment by gartha1** [comment]
thanks, got it working now, I missed something silly on the wireshark interface partly as I hadn't used it in years.
