### ISSUE TITLE
permanent set value pcap_setmintocopy

### ISSUE THREAD

**Issue by tuanlinh225** [nmap/npcap#607]
Dear 
I am looking for npcap default value store location. 
for example : where does the default value of pcap_setmintocopy setting location ?
Just want to permanent change this setting value
Thank you so much

**Comment by markpizz** [comment]
Why don't you merely change this in the application that uses Npcap?

**Comment by dmiller-nmap** [comment]
The default value is defined in `/wpcap/libpcap/pcap-npf.c` in `pcap_activate_npf()`. If the user application has not set immediate mode (`pcap_set_immediate_mode()`), the default value is 16KB (16000 bytes). It is not possible to change this without rebuilding wpcap.dll.
