### ISSUE TITLE
Npcap 1.70 PacketOpenAdapter returns empty string for ADAPTER.Name

### ISSUE THREAD

**Issue by DarkDarro** [nmap/npcap#609]
Call Npcap API PacketOpenAdapter with a specific device string.
In our case the device is a virtual ethernet adapter if it is relevant.
The returned ADAPTER object's "Name" member is an empty string "".

In Npcap 1.60 the device string parameter of PacketOpenAdapter was the same as the member after a successful call and we reused the member later on as a parameter to API pcap_open_live.

In Npcap 1.70 this now fails with the empty string.

**Comment by fyodor** [comment]
Just as an update, @dmiller-nmap and I were chatting about this and it looks like we'll probably be able to add back the Name for the Npcap 1.71 release, which we're hoping to put out next week.  Still, as Dan mentioned so persuasively above, it's best to avoid calling the Packet API if possible.  We and the libpcap team work had to maintain the wpcap (libpcap) API, but Packet is meant to be an internal API with no compatibility guarantees.  I'll re-open this so we can close it after we put Name back.

**Comment by DarkDarro** [comment]
Thanks for the information.
I can delegate to the customer, that future releases should use the expected API functions.
The code had been like this even with the last winpcap release and then continued with Npcap 0.9995.
Older versions of the product had already been released which would have failed to run when people decided to manually update Npcap to 1.70 or had it already installed prior to the product installation.

**Comment by fyodor** [comment]
Thanks for the extra details @DarkDarro.  If you are bundling Npcap OEM 1.60 with your product, that means you must have an Npcap OEM redistribution license and thus are probably entitled to priority support.  If you don't have your support contact details, feel free to write to sales@nmap.com and they will hook you up.  What sometimes works best is to file an issue here and then provide the issue number to support so they know to mark it high priority and start work on it ASAP.
