### ISSUE TITLE
Npcap Bug Report

### ISSUE THREAD

**Issue by acesleong2** [nmap/npcap#620]
My wireshark did not have ethernet interface

**Comment by dmiller-nmap** [comment]
Please provide the information requested in the [bug report template](https://github.com/nmap/npcap/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and the [Npcap Guide](https://npcap.com/guide/npcap-users-guide.html#npcap-issues), specifically:
1. Versions of Npcap and Wireshark you are using.
2. Output of [DiagReport](https://npcap.com/guide/npcap-users-guide.html#npcap-issues-diagreport)
