### ISSUE TITLE
Npcap OEM 1.71: After return from windows power save mode "PacketReceivePacket" and "PacketSendPacket" returns often with "ERROR_DEVICE_REMOVED"

### ISSUE THREAD

**Issue by ha-andy** [nmap/npcap#627]
I tested the workaround i.e. skipped the first return value "1617" and called the Npcap API again after a Windows API SleepEx with a sleep time of 120 seconds. The return value was still "1617" only rarely it succeeded without error.
The network adapter is pingable during the SleepEx.

This issue is still there:
https://github.com/nmap/npcap/issues/506

**Comment by fyodor** [comment]
Just as an update, Npcap Version 1.73. has been released and we believe this is fixed.  So I'm closing this.  But if anyone still encounters the problem, please post and we'll re-open.
