### ISSUE TITLE
Upgrade Npcap build system to Visual Studio 2022

### ISSUE THREAD

**Issue by fyodor** [nmap/npcap#629]
We currently build Npcap using Visual Studio 2019 (VS2019) but should probably upgrade to VS2022.  Among the improvements are ARM64X support which is important for supporting x64 applications on the Windows on ARM platform as discussed in #585 .

We are planning this upgrade for the Nmap build system too.  See https://github.com/nmap/nmap/issues/2520.

**Comment by dmiller-nmap** [comment]
Npcap 1.80 was built with VS2022, apart from the Windows 7 through 8.1 drivers.
