### ISSUE TITLE
Win7 PAE (patch) and Windows Server 2008 (32bit) BSOD

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [nmap/npcap#631]
well seems this driver is not PAE compatible
need to follow driver guidelines for it to be :)

**Comment by fyodor** [comment]
Thanks for opening the issue, but there really isn't enough for us to go on from your description.  Feel free to open a new one with more details about your setup and the symptoms if you'd like.

**Comment by fyodor** [comment]
Thanks @MyTDT-Mysoft.  This does help explain it better.  Are you able to reproduce this issue on any version of Windows still supported by Microsoft?  I believe that MS stopped providing even their special paid security updates ("extend support") for Win7 and Server 2008 back in January 2020.  I will close this issue for now but can re-open if it can be demonstrated to affect any version of Windows that Microsoft still supports.

**Comment by MyTDT-Mysoft** [comment]
> Thanks @MyTDT-Mysoft. This does help explain it better. Are you able to reproduce this issue on any version of Windows still supported by Microsoft? I believe that MS stopped providing even their special paid security updates ("extend support") for Win7 and Server 2008 back in January 2020. I will close this issue for now but can re-open if it can be demonstrated to affect any version of Windows that Microsoft still supports.

hum... well as for server 2008 is the latest 32bit one... but yes the same will happen on wndows 10.... 32bit with PAE patch (to unlock the 4gb limit), i could try to install that on a VM to test it...

but i wont bother if you will just ignore it... because it requires a patch to disable the 4gb... requirement that only exist because of buggy drivers like this one :P

**Comment by spv420** [comment]
@MyTDT-Mysoft i'd like to inform you that macOS Catalina dropped support for 32-bit entirely, and most people have been doing fine without it. not for 32-bit hardware, but for 32-bit software, 32-bit hardware died long ago, and was unsupported in Snow Leopard.
