### ISSUE TITLE
NSOCK ERROR [0.1970s] ssl_init_helper(): OpenSSL legacy provider failed to load and Error compiling our pcap filter: expression rejects all packets

### ISSUE THREAD

**Issue by Aholicknight** [nmap/npcap#633]
**Describe the bug**
NSOCK ERROR [0.1970s] ssl_init_helper(): OpenSSL legacy provider failed to load and Error compiling our pcap filter: expression rejects all packets when trying to scan a IP address.

**To Reproduce**
1. Open zenmap with nmap version 7.93
2. Scan a IP address
3. Error will popup

**Expected behavior**
Scan to complete

**Screenshots**
![zenmap_6488817499](https://user-images.githubusercontent.com/7843719/190261220-b784a580-16d4-4025-ac12-6bda1061111a.png)

**Diagnostic information**
* OS Name	Microsoft Windows 11 v10.0.22000.856
* Output of DiagReport: https://pastebin.com/PByFtT4M
* Any special hardware or software that may be relevant: VPN, firewall, antivirus, virtualization (SR-IOV passthrough, etc): OpenVPN version 2.5.5

**Additional context**
I am currently connected to a VPN via OpenVPN during the scan.

**Comment by SuLLLivaN** [comment]
I installed npcap-0.992, and it fix the problem

**Comment by Aholicknight** [comment]
Installing npcap-0.992 fixes this problem.

**Comment by Aholicknight** [comment]
Installing npcap-0.992 fixes this problem.

**Comment by bigretromike** [comment]
NSOCK ERROR is more of information not error.
0.992 did not fix same issue on my side.
Just saying for those fighting
