### ISSUE TITLE
Npcap extremely slowing down connectivity at boot WIN10

### ISSUE THREAD

**Issue by crankedguy** [nmap/npcap#65]
Hi,

at least in latest Windows 10 version with all patches applied npcap extremely, really extremely slows down connectivity at startup. I would not bother if we were talking about 5 seconds here, but I have to wait like 40-50 seconds on boot to get network connectivity as soon as npcap is installed.
It is not system specific, it is the same on my laptop with wireless as on my desktop with just Ethernet. 
Installed : 
driver not started at boot time...I don't want that 
and for the rest it makes absolutely no difference if 
loopback yes/no,
compatibility mode yes/no,
admin restriction yes/no
it is just always the same, tried on 2 computers as said.
Waiting a minute is too much.

Any ideas here on what that could be or how to investigate? As said I don't think it makes sense to investigate too deeply for a specific system computer problem

Thanks

**Comment by dmiller-nmap** [comment]
Closing this issue: the delay for optional NDIS LWF drivers is well-documented.
