### ISSUE TITLE
NPCAP 1.71 & 1.72 is not completely removed after an unistall

### ISSUE THREAD

**Issue by N0Name68** [nmap/npcap#657]
After an uninstallation the service is still running, just stopped: (first execution of the command was before the uninstallation , the second after)
![grafik](https://user-images.githubusercontent.com/122433666/211745797-73c4a6e2-dd13-45d0-8005-cf4846390200.png)

After a reboot the service is still installed, the status is stopped and the Win32ExitCode is often 0x1F. 

The service can not be started:
![grafik](https://user-images.githubusercontent.com/122433666/211746752-99eb4fcb-2e41-4b45-883e-95e1422254dd.png)

To Reproduce
1. Install NPCAP 1.71 or 1.72
2. Uninstall NPCAP via windows Apps and Features or with the uninstaller
3. Check if the service is still installed 

Expected behavior
Before version 1.71 ther service was not longer available after an uninstall

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. We will investigate for correction in the next release. In the meantime, you can remove the leftover service stub by running the following command as Administrator: `sc.exe delete npcap`
