### ISSUE TITLE
Failed to create Npcap service: 0x800f0203

### ISSUE THREAD

**Issue by Jcouch23** [nmap/npcap#660]
I am unable to download npcap service which is critical for my job.
[install.log](https://github.com/nmap/npcap/files/10818566/install.log)
[NPFInstall.log](https://github.com/nmap/npcap/files/10818567/NPFInstall.log)

**Comment by ANSUUVIOUS** [comment]
I see that you're missing three DLLs that is preventing you from installing this:

IfFileExists: file "C:\WINDOWS\system32\packet.dll" does not exist, jumping 1334
IfFileExists: file "C:\WINDOWS\system32\wpcap.dll" does not exist, jumping 1337
IfFileExists: file "C:\WINDOWS\system32\pthreadVC.dll" does not exist, jumping 1340

so you may need to figure out where to get these files first installed

**Comment by Jcouch23** [comment]
Was able to get our IT to reimage PC and it corrected issue.

Thanks
***@***.***[Johnson Controls Logo]
Jarod Couch
Metro Market Lead System Specialist
Austin, TX Area

24 Hour Service
Austin 866-819-0231
Temple/Waco 866-928-8120

Mobile: 512-316-9395
Email: ***@***.******@***.***>

**Comment by ANSUUVIOUS** [comment]
you should close the issue then to avoid having anyone else trying to help the situation

**Comment by guyharris** [comment]
> IfFileExists: file "C:\WINDOWS\system32\pthreadVC.dll" does not exist, jumping 1340

Why is pthreadVC.dll involved?  I don't think there's anything in Npcap that requires it (rpcapd uses Windows threads. not pthreads, on Windows; the seltotest test program uses pthreads, but it isn't intended to be built or run on Windows, it's a UN*X-only program).
