### ISSUE TITLE
What Visual Studio version should *libpcap* make the minimum required version?

### ISSUE THREAD

**Issue by guyharris** [nmap/npcap#67]
Currently, I've been trying to allow it to work with VS 2013, although I can't guarantee that I've succeeded there.

[The npcap README.md](https://github.com/nmap/npcap/blob/master/README.md) says, as of the time I'm filing this issue, that:

> The DLLs need to be built using **Visual Studio 2013**. And the driver needs to be built using **Visual Studio 2015** with **Windows SDK 10 10586** & **Windows Driver Kit 10 10586**. 

Does "the DLLs" include the libpcap DLL (`npcap.dll` or whatever it's called)?  If not, what VS version is it built with?

(If it requires VS 2015, including the VS 2015 runtime, or a later version, I can use `snprintf()` directly, and can use it to make an "generate a `malloc()`ed formatted string that's large enough" routine and use that in some places, as long as I kick to the curb some older UN\*X versions of `snprintf()` with non-C99 behavior, which I'm willing to do.)

**Comment by dmiller-nmap** [comment]
Closing this since libpcap has made their decision. For reference, Npcap's builds are all done with VS 2019 currently, and we intend to keep updating so that we will always use either the latest stable or the immediately-prior version supported by Microsoft.

**Comment by guyharris** [comment]
> I've switched the AppVeyor builds for libpcap to use VS 2015 (tcpdump was already using it).

Still requires, and allows, 2015 or later in CMakeLists.txt.  Appveyor currently tests against 2015, 2017, and 2019, both 32-bit and 64-bit.
