### ISSUE TITLE
Npcap "pcap compatibility" still not working?

### ISSUE THREAD

**Issue by asctime** [nmap/npcap#672]
Have multiple pcap driven apps (mostly 64 bit, but not all) compiled against various native versions of libpcap on Windows 10. Run without issue using legacy driver 4.1.3. Npcap is "seen" (e.g. no waring box in [MinGW Wireshark](https://gitlab.com/wireshark/wireshark/-/issues/17771)) but no interfaces are actually detected.

Npcap has been "advertising" pcap compatibility for some time now. I have tried multiple releases but could never get it to work.

Are there some documented nuances around this, or is it truly hit-and-miss?

**Comment by fyodor** [comment]
Hi @asctime.  It will work best if you can recompile the software using Npcap SDK and modern compiler tools.  We still support the same API.  But WinPcap itself was abandoned more than 10 years ago and so there are many layers of compatibility needed for software compiled against it way back then to still work.  And the Windows OS and Visual Studio compiler tools diverge more each year from how they worked back then.  So the binary compatibility for using modern Npcap with apps compiled long ago for WinPcap probably gets a bit worse every year.  And the number of requests we get for supporting specific WinPcap apps has dwindled to near-zero as well.  Any actively maintained project should have moved on long ago given that the WinPcap download page literally warns people not to use it any more.

So yeah, I think your "hit or miss" characterization is probably fair.  If you really need to run some old binary which was compiled against WinPcap long ago, and you can't recompile it, and it doesn't work with newest Npcap, then you could try older versions of Npcap or even see if you can get WinPcap itself working on the system.  Cheers.
