### ISSUE TITLE
Npcap Bug Report - unable to install npcap 1.75 on Windows 10, service creation fails

### ISSUE THREAD

**Issue by ScottishRob** [nmap/npcap#673]
While exploring other VLAN issues, I wanted to view 802.1d tags, so I went to start Wireshark (4.0.5).  It failed, as npcap (1.5) wasn't running.  It was then I went down the rabbit hole.  I now have no operational npcap on my primary debug PC.  Installation of 1.75 fails, as it cannot create the npcap service.  Can't find anything telling in the logs.

Windows 10 22H2 19045.2846
NPCAP 1.75
nmap 7.91
Wireshark 4.0.5 (leaving this uninstalled until I get npcap 1.75 installed and working)

npcap installed for Administrators only, and no WinPcap compat mode.

[DiagReport-20230506-164906.txt](https://github.com/nmap/npcap/files/11412803/DiagReport-20230506-164906.txt)

Tried removing wpcap.dll, packet.dll, and the Npcap directory from C:\Windows\System32\ and C:\Windows\SysWOW64\ and doing a reinstall of npcap.  Same outcome.  No service created, no operational driver.

Directory list of C:\Program Files\npcap\

```
PS C:\Program Files\Npcap> dir

    Directory: C:\Program Files\Npcap

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          22/11/2022    19:25            815 CheckStatus.bat
-a---          06/05/2023    16:49          40588 DiagReport-20230506-164906.txt
-a---          22/11/2022    19:25           1073 DiagReport.bat
-a---          22/11/2022    19:25          18078 DiagReport.ps1
-a---          22/11/2022    19:25           2513 FixInstall.bat
-a---          06/05/2023    16:48          26790 install.log
-a---          22/11/2022    19:25          11784 LICENSE
-a---          27/04/2023    14:51           2436 npcap_wfp.inf
-a---          27/04/2023    14:51          12730 npcap.cat
-a---          27/04/2023    14:51           9004 npcap.inf
-a---          27/04/2023    14:51          78376 npcap.sys
-a---          26/04/2023    22:54         308688 NPFInstall.exe
-a---          06/05/2023    16:48         146233 NPFInstall.log
-a---          27/04/2023    14:59        1083400 Uninstall.exe
```

I just don't believe this line from install.log:

DetailPrint: The npcap service was successfully created

[install.log](https://github.com/nmap/npcap/files/11412825/install.log)

No group policy changes since previous npcap 1.5 with nmap and wireshark were installed.

Any help here much appreciated.

**Comment by ScottishRob** [comment]
Hey Daniel.  Did the above, left Wifi filter deselected, selected Winpcap mode.

1) Removed Wireshark and npcap 1.75, checked for any presence of Winpcap (none).
2) Rebooted - no issues
3) Installed npcap 1.71 with nmap 7.91 no Wifi filter enabled and Winpcap emulation checked.
4) No npcap service is created.  NPF loopback device is present.

```
C:\Program Files\Wireshark>dumpcap.exe -D
1. \Device\NPF_Loopback (Adapter for loopback traffic capture)

C:\Program Files\Wireshark>
```

So I removed npcap 1.71, then rebooted.  After the reboot Windows strangely told me that npcap was still installed, but couldn't find the **uninstaller**, so I removed the registry entry for the uninstaller to match the system state.  I then manually removed the C:\Program Files\npcap folder completely.  There was one solitary error in install.log regarding possible permissions in there.  Not sufficient detail to identify the root cause, unfortunately.

I then rebooted and ran the npcap 1.75 installer once again, with Admin only, Wifi filter (why not), and WinPcap API compat mode.

Logs below.  **Still no creation of the npcap service** <-- this is where I'm digging currently.

Only this error in DiagReport:

```
*************************************************
Service Info:
*************************************************
Get-Service : Cannot find any service with service name 'npcap'.
At C:\Program Files\Npcap\DiagReport.ps1:212 char:1
+ Get-Service npcap
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (npcap:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
 
Get-Service : Cannot find any service with service name 'npf'.
At C:\Program Files\Npcap\DiagReport.ps1:214 char:1
+ Get-Service npf
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (npf:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
```

Files you asked for:

[NPFInstall.log](https://github.com/nmap/npcap/files/11437112/NPFInstall.log)

[DiagReport-20230510-014746.txt](https://github.com/nmap/npcap/files/11437114/DiagReport-20230510-014746.txt)

nmap -d --iflist
[npcap-nmap-iflist.txt](https://github.com/nmap/npcap/files/11437132/npcap-nmap-iflist.txt)

Really glad this laptop has only RFC1918 addresses!  Additional detail, due to desperation, Powershell 5 and 7 both installed (I manage them both to run PowerCLI for VMware).  VMware Workstation and Hyper-V both installed.  Wireshark and nmap have given me many years of faultless service, on this same build - so I know both work(ed)!

**Comment by ScottishRob** [comment]
Where are the Windows npcap and npf services created?  I can't find anything in the NPFInstaller code tree anywhere.  I'm close to wanting to build this on this PC with symbols and debug it to find out why registry entries are missing and the services aren't being created.

I temporarily disabled my AV scanning, and I set a local group policy (Prevent installation of devices using drivers that match these device setup classes) to disabled, that "might" have affected the installation of a driver.  No change.

**Comment by alglove** [comment]
There may be some corrupt privileges within the Windows Registry that do not allow the new installation to write its entries correctly. I have run into similar issues when trying to install other programs and services. I am not a developer, so I may be missing some, but I believe these are service entries:

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npcap
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npcap_wifi

Try uninstalling npcap, reboot, then delete the registry entries shown above. If they delete, great! Try reinstalling and see if that works for you.

If the registry entries do not delete, you will probably get some Windows message complaining about insufficient privileges to delete. (This would also prevent the software from installing correctly.) To get around this, right-click on the registry key and choose "Permissions..." to change the privileges to allow you to delete it. I do not remember the exact procedure (sometimes you have to take ownership, as well), but that is the basic idea.

Hopefully this helps.

**Comment by ScottishRob** [comment]
Hi alglove

No difference.  Removing npcap did not delete that hive, however no issues removing it in regedit, and no difference after installing npcap 1.75 again.  Still no npcap service is created.

In Windows event manager, same time as installation, Event ID 7000.

```
The Npcap Packet Driver (NPCAP) (Wi-Fi) service failed to start due to the following error: 
The system cannot find the file specified.
```

Could use some guidance on where in the repo to find the code that creates the service, and to identify which file is referred to in this event.

Thanks.

**Comment by alglove** [comment]
Hi, ScottishRob.

Well, at least the registry permissions seem to be OK.

You may be able to find that "file specified" in the Event Viewer message itself. In the bottom half of the Event Viewer. Where you see the message on the bottom half, there are two tabs: "General" and "Details". These tabs are really easy to miss if you are not looking for them. Click on the "Details" tab, and then you will see a "Friendly View" and an "XML View". Try looking through those for the filename. There is a lot of data there that does not make it to the main message.

**Comment by ScottishRob** [comment]
Only this:
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" /> 
  <EventID Qualifiers="49152">7000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2023-05-12T00:47:32.8369611Z" /> 
  <EventRecordID>1862746</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="1924" ThreadID="21796" /> 
  <Channel>System</Channel> 
  <Computer>sikorsky.corp.cirrologic.com</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="param1">Npcap Packet Driver (NPCAP) (Wi-Fi)</Data> 
  <Data Name="param2">%%2</Data> 
  <Binary>6E0070006300610070005F0077006900660069000000</Binary> 
  </EventData>
  </Event>
```

So %%2 ... and related to the WiFi filter, which I'm not fussed about.  If I deselect it during install, no error.

BTW: Right clicking on the npcap.inf file in C:\Progarm Files\npcap and selecting install, says "success", still without creating the service.

**Comment by ScottishRob** [comment]
Sigh.  And there it is.  The fckening.  I disabled protection in Kaspersky Endpoint Security 12.0.0.465, and I also disabled "Self-defense" (In the Application Settings menu page, 3rd group down - deselect "Enable Self-Defense"), then I rebooted (it didn't setup the service until I rebooted).

Now, I get an Admin-Helper alerts for EVERY interface, and I have 20 of them, so I start with "Run as Administrator" and we're all good.

What I think is missing/hard here, is debug information to show me what failed, where it failed, so I could have got to AV filter program is watching the filter stack and preventing the creation of a service.  There was nothing in the KES debug logs, and Wireshark/Nmap were giving me nothing in the logs either.

I have something to learn here, as relying on trial and error isn't a Good Thing(tm) in this marvellously technical world of ours.

Thanks for the inputs above.  Much appreciated.

**Comment by de-served** [comment]
> I have the same problem here, after upgraded npcap 1.75 from 1.71 on windows 11, the service can't be installed, and all old versions of npcap's services can't be installed. After uninstalling and rebooting and installing again, with all options selected, it did not solve the problem [npcap_1.75_install.log](https://github.com/nmap/npcap/files/11538353/npcap_1.75_install.log)
> 
> After turning off Kaspersky protection and self-protection, I successfully installed it. Turning off Kaspersky Protection alone doesn't seem to solve the problem.

I've got same problems from this whole topic. Nothing happened at all. Digged that cmd: "C:\Programs\_System\npcap\NPFInstall.exe" -n -i leads to 0x80070002 without any explanation. Safe mode, cleaning registry/filesystem for any left records/files (almost none or none absolutely), comparing with VM, where I installed npcap successfully each try - what changes in filesystem, in registry - nothing helped at all.
Except this "...Kaspersky self-protection".
I read it and momentarily remember that I've just enabled it two days ago. Before this it was disabled. And my first npcap install before this was successful and I've used Wireshark for a few days but then decided to find a way to install npcap to specified directory, found /D= option, uninstalled npcap and... after that I wasn't able to install it back, to default or not default directory. Until now. Unchecked self-protection, cleaned setupapi.dev.log, cleaned oem*.infs's with pnputil "for" cycle [somewhere found to try this], then now it is successfully installed, registry records are ok (when was not ok there was just "Start" key in CurrentControlSet\Services\npcap) - now there are ImagePath and other keys.
Wireshark now works again.
Big thanx!

PS: npcap installer can [must] check if service is installed successfully or not (net start npcap = no service installed) and can warn to turn off self-protection in kaspersky if kaspersky found, service is not installed and NPFInstall throws 0x80070002.

**Comment by gvanem** [comment]
I also had problem with a `net start npcap` after todays [Fat Patch WinUpdate](https://krebsonsecurity.com/2024/02/fat-patch-tuesday-february-2024-edition/). 

Then looking in the Registry, I noted some `REG_EXPAND_SZ` entries for `\SystemRoot\DRIVERS\npcap.sys` where it should have been  `%SystemRoot%\DRIVERS\npcap.sys`! How is this possible?
