### ISSUE TITLE
Winpcap + npcap: some packets not received after loosing ethernet connection

### ISSUE THREAD

**Issue by christophe-calmejane** [nmap/npcap#680]
Hi, 
this is a follow up of #655 , same behavior but not the same way to trigger the bug. I should add that #655 (which was actually #647) was indeed solved in npcap 1.72.

This new issue is affecting 1.70 though 1.75 (current version at this date) and here is the way to reproduce it.

**To Reproduce**
1. Start an application that will try to load winpcap, and set up a single filter: `"ether proto 0x22f0"`
2. Start Wireshark (a version using npcap natively if present, not winpcap)
3. Setup a filter to display AVDECC messages `"ieee17221"`
4. Have a device sending AVDECC messages, like a Mac computer (need to setup correctly the interface by enabling AVB through `avbutil`)
5. Observe in wireshark `AVDECC Discovery` messages (ieee1722.subtype==0xfa)
6. *Unplug the ethernet cable from the switch* for a couple seconds
7. *Plug the cable again*
8. Observe in wireshark that no `AVDECC Discovery` messages are received anymore, but other AVDECC messages are correctly received.
9. Restarting the application using winpcap **and** wireshark causes messages to be received once again

**Expected behavior**
Continue to receive all messages when using winpcap and npcap altogether.

**Additional context**
* What I noticed is that only `MULTICAST` messages are no longer received, all other messages (including other AVDECC unicast messages) are properly received by applications using npcap (`packet filter` issue I suppose, like explained in #647)

**Comment by dmiller-nmap** [comment]
Since reception of multicast messages is controlled by the hardware packet filter (a NDIS stack feature), it is possible that this issue is related to #710 and fixed in Npcap 1.79. Please let us know if this issue affects Npcap 1.79, otherwise we will consider it resolved.

**Comment by christophe-calmejane** [comment]
I'll check this shortly, thanks for the notice.

**Comment by christophe-calmejane** [comment]
Hi,
I'm unfortunately unable to reproduce the issue even with an older npcap version, so I cannot check if it has been fixed or not. Maybe it has something to do with my windows version that is different than 6 months ago (still windows 11, but with more patches).
Let's just close it, I'll keep monitoring it anyway (if I find a computer that has the issue).
Thanks.
