### ISSUE TITLE
Not an Issue but a question

### ISSUE THREAD

**Issue by pbonda01** [nmap/npcap#686]
I am not a C/C++ developer but trying so is anyone able to point me in the right direction please where I can find the logic/code that creates the "NPCAP Packet Driver (NPCAP)" under the Ethernet Properties? I'm trying to see how this was done for this particular project. Thank you for your help and direction.

**Comment by fyodor** [comment]
I'm closing this as it's not a "real issue" we need to track for development purposes, but anyone who wants to can still answer.
