### ISSUE TITLE
npcap stops EtherNet/IP responses

### ISSUE THREAD

**Issue by MusaMan** [nmap/npcap#69]
Hello 

I am using Wireshark with npcap on Windows 7 to develop an EtherNet/IP client application. Setup is as follows: My development PC -> VPN into the office -> EtherNet/IP Device connected to network. I have been using Npcap 0.99-r8 and Npcap 0.99-r7 - the issue is the same.

Test scenario:
- Start test application, send any EtherNet/IP request packet (e.g. List Identity, using UDP unicast)
=> Response is successfully received
- Start WireShark witn NPcap driver, select appropriate NdisWan Adapter.
- Send any EtherNet/IP request packet (e.g. List Identity, using UDP unicast)
=> Request packet can be seen in Wireshark, but no response.
=> Subsequent request packets can be seen in Wireshark, but no response.
- Stop logging or Exit WireShark
- Send any EtherNet/IP request packet (e.g. List Identity, using UDP unicast)
=> Response is successfully received

I use my own EtherNet/IP client software or the free Molex EtherNet/IP tool, which is great for showing this issue. Download: https://www.molex.com/mx_upload/superfamily/iccc/EtherNet_IPTool.html
Usage: Start tool, stay on first tab (List Identity), Message Type 'Unicast', enter IP address of target device, press 'Send List Identity Request on UDP'. If successful, 'Station' (device) will show up in the frame to the right, otherwise not.

Thanks.

**Comment by dmiller-nmap** [comment]
Upon further analysis, this is most likely a duplicate of nmap/nmap#1343, which was fixed in Npcap 0.9990. If this problem persists, please open a new issue and refer to this one there.
