### ISSUE TITLE
npcap disables RSC (Receive Side Coalescing)

### ISSUE THREAD

**Issue by rossro** [nmap/npcap#70]
npcap installation causes RSC (Receive Side Coalescing) to be disabled with failure reason "NDISCompatibility". In this case, this is OS software RSC that was introduced in Win10 RS2. I believe that it is enabled by default for devices that do not supports RSC (in HW). Below is the output of  "Get-NetAdapterRsc" before and after npcap installation:

PS C:\>  Get-NetAdapterRsc *
Name                           IPv4Enabled  IPv6Enabled  IPv4Operational IPv6Operational IPv4FailureReason IPv6FailureR
                                                         State           State                             eason
----                           -----------  -----------  --------------- --------------- ----------------- ------------
Wi-Fi                          True         True         True            True            NoFailure         NoFailure

PS C:\>  Get-NetAdapterRsc *
Name                           IPv4Enabled  IPv6Enabled  IPv4Operational IPv6Operational IPv4FailureReason IPv6FailureR
                                                         State           State                             eason
----                           -----------  -----------  --------------- --------------- ----------------- ------------
Wi-Fi                          True         True         False           False           NDISCompatibility NDISCompa...

**Comment by dmiller-nmap** [comment]
Npcap has been updated to NDIS 6.20. This does not directly address the issue of RSC, but it is an important first step in our overall plan to support a separate NDIS 6.50 build for Windows 10 and keep NDIS 6.20 for earlier Windows versions. The Windows 10 driver would then support RSC, allowing us to close this issue.

**Comment by dmiller-nmap** [comment]
This issue is resolved for Windows 10-based systems (including Server 2016 and 2019) in Npcap 0.9995, which uses NDIS 6.50 and opts-in to large frame support in WFP.

**Comment by jgmoras** [comment]
FYI - added comment on BSOD issue - https://github.com/nmap/npcap/issues/206#issuecomment-663530168

I can confirm the NDIS update did indeed allow for RCS working and faster speeds but introduced a BSOD ( or system hang in my situation )
