### ISSUE TITLE
Silent upgrades

### ISSUE THREAD

**Issue by joachimlindenberg** [nmap/npcap#700]
I do understand that silent installs are a OEM license thing. However I am just using Wireshark on a number of systems, and while Wireshark itself does support a silent upgrade, npcap does not. As I want my systems to be consistently up-to-date, I automated lots of upgrades (and no installs), and npcap´s lack of silent upgrade is definitely an inconvenience.
Can you please consider to support silent upgrades?
Thanks,
Joachim

**Comment by fyodor** [comment]
Hi Joachim.  Wireshark comes with the demo version of Npcap which has the advantage of being completely free, but as you note it doesn't include a silent installer for automated deployment and upgrades.  It only takes a few clicks to install, but we also sell Npcap OEM Edition which has an entirely silent installer.  That's how we fund the Npcap Project. You can find [details and prices here](https://npcap.com/oem/internal.html).
