### ISSUE TITLE
failed to set hardware filter to promiscuous mode (see Additional Context)

### ISSUE THREAD

**Issue by PsycloneTM** [nmap/npcap#702]
**Describe the bug**
After updating my LAN drivers this message came up.

**To Reproduce**
1. Open Wireshark
2. Click LAN adaptor
3. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/nmap/npcap/assets/27637025/f36ed2c1-d3c5-4cbe-9686-36c7ada1064c)
![image](https://github.com/nmap/npcap/assets/27637025/eb95afb6-ae3b-4506-bd79-ccf03f4d34e5)

**Additional context**
The reason for this issue is Wireshark installs NPCAP 1.71 as you can see in the screenshot above. I realize this isn't the Wireshark GitHub not that there is one but if you have any contact with Wireshark I'd strongly urge you to tell them about this issue as the average user won't know this is the issue.

**Comment by guyharris** [comment]
> I realize this isn't the Wireshark GitHub not that there is one

There isn't a Wireshark GitHub because Wireshark is on GitLab, not GitHub.

Please file this issue on [the Wireshark issue list](https://gitlab.com/wireshark/wireshark/-/issues/); I suggest giving it a title such as "failed to set hardware filter to promiscuous mode due to Wireshark 4.0.x installing Npcap 1.71".

**Comment by PsycloneTM** [comment]
> Please file this issue on [the Wireshark issue list](https://gitlab.com/wireshark/wireshark/-/issues/); I suggest giving it a title such as "failed to set hardware filter to promiscuous mode due to Wireshark 4.0.x installing Npcap 1.71".

How does this look? https://gitlab.com/wireshark/wireshark/-/issues/19420

**Comment by guyharris** [comment]
Looks good.
