### ISSUE TITLE
Crash when using pcap_findalldevs_ex.

### ISSUE THREAD

**Issue by zzc-1024** [nmap/npcap#705]
**Describe the bug**
When I use pcap_findalldevs_ex, the program can be compiled successfully, but it can't run.

**To Reproduce**
It can be used at start. But when I update the npcap from 1.71 to 1.78, it dosen't work anymore.

**Expected behavior**
Program can be executed.

**Screenshots**
![image](https://github.com/nmap/npcap/assets/67462033/aedb2bca-1235-437a-8ece-a29fdc7294b9)

**Diagnostic information**
* Windows 11
* x64
* SDK version 1.13

**Additional context**
```C++
#include <stdio.h>
#include <string>
#include <pcap.h>

using namespace std;

void PrintLine(int x)
{
  for (size_t i = 0; i < x; i++)
  {
    printf("-");
  }
  printf("\n");
}

int enumAdapters()
{
  pcap_if_t *allAdapters;
  pcap_if_t *ptr;
  int index = 0;
  char errbuf[PCAP_ERRBUF_SIZE];

  if (pcap_findalldevs_ex(PCAP_SRC_IF_STRING, NULL, &allAdapters, errbuf) != -1)
  {
    PrintLine(100);
    printf("index \t des \n");
    PrintLine(100);

    for (ptr = allAdapters; ptr != NULL; ptr = ptr->next)
    {
      ++index;
      if (ptr->description)
      {
        printf("[ %d ] \t [ %s ] \n", index - 1, ptr->description);
      }
    }
  }

  pcap_freealldevs(allAdapters);
  return index;
}
int main(int argc, char* argv[])
{
  enumAdapters();
  system("pause");
  return 0;
}

```

**Comment by gvanem** [comment]
Works fine for me with the official libpcap:
```
----------------------------------------------------------------------------------------------------
index    des
----------------------------------------------------------------------------------------------------
[ 0 ]    [ Network adapter 'Microsoft' on local host ]
[ 1 ]    [ Network adapter 'Microsoft' on local host ]
[ 2 ]    [ Network adapter 'Realtek PCIe GbE Family Controller' on local host ]
[ 3 ]    [ Network adapter 'Realtek PCIe 2.5GbE Family Controller' on local host ]
[ 4 ]    [ Network adapter 'ExamplePlugin #2' on local host ]
[ 5 ]    [ Network adapter 'ExamplePlugin #1' on local host ]
```

PS. What is `using namespace std;` good for?

**Comment by zzc-1024** [comment]
Thank you for your reply. I still haven't found a solution, but it works in another machine. I can't reiably reproduce this problem.
Besides, `using namespace std;` is useless in the code actually, I forgot to remove it.

**Comment by zzc-1024** [comment]
Thanks for your advice. I checked its dependencies and found that it was missing `packet.dll` and `wpcap.dll`.

**Comment by zzc-1024** [comment]
Thank you for your patient help. Finally, I solved the problem.
When installing Npcap, the API-compatible mode must be selected.
![image](https://github.com/nmap/npcap/assets/67462033/011900aa-0c50-4f19-8f34-c081aff00712)
