### ISSUE TITLE
Can Npcap use KeQuerySystemTimePrecise() if running on Windows 8 or later?

### ISSUE THREAD

**Issue by guyharris** [nmap/npcap#71]
[Somebody complained about packet time stamps drifting from system time with WinPcap on Windows 10](https://ask.wireshark.org/question/6330/frame-arrival-time-drift/).

WinPcap has, at least on 32-bit Windows, a registry parameter `HKLM\System\CurrentControlSet\Services\NPF\TimestampMode` that controls how time stamps are generated:

- 0 (default) -> Timestamps generated through KeQueryPerformanceCounter, less reliable on SMP/HyperThreading machines, precision = some microseconds
- 2 -> Timestamps generated through KeQuerySystemTime, more reliable on SMP/HyperThreading machines, precision = scheduling quantum (10/15 ms)
- 3 -> Timestamps generated through the i386 instruction RDTSC, less reliable on SMP/HyperThreading/SpeedStep machines, precision = some microseconds

There also appears to be a setting of 1, the symbol for which in `time_calls.h` is `TIMESTAMPMODE_SYNCHRONIZATION_ON_CPU_WITH_FIXUP`, and a setting of 99, the symbol for which is `TIMESTAMPMODE_SYNCHRONIZATION_ON_CPU_NO_FIXUP`.

It looks as if, on 64-bit Windows, the RDTSC version isn't supported.

From a quick look at the Npcap driver, it seems to behave similarly, although the NT `GET_TIME()` code went from

```
#ifdef _X86_
	if ( TimestampMode == TIMESTAMPMODE_RDTSC )
    	{
		GetTimeRDTSC(dst,data);
	}
	else
#endif // _X86_
	if ( TimestampMode == TIMESTAMPMODE_QUERYSYSTEMTIME )
	{
		GetTimeQST(dst,data);
	}
	else
	{
		GetTimeKQPC(dst,data);
	}
```

in WinPcap to

```
#ifdef _X86_
	if (g_TimestampMode == TIMESTAMPMODE_RDTSC)
	{
		GetTimeRDTSC(dst, data);
	}
	else
		#endif // _X86_
	if (g_TimestampMode == TIMESTAMPMODE_QUERYSYSTEMTIME)
	{
		GetTimeQST(dst, data);
	}
	else
	{
		GetTimeKQPC(dst, data);
	}
```

on Npcap - the mis-indentation of the `#endif` makes it less clear that modes 0 and 2 are still supported.

If a mode were supported in which `KeQuerySystemTimePrecise()` were used, at least on Windows 8 (and its server variant) and later, that would provide a mode that 1) gives high-resolution time stamps and 2) doesn't drift from the system clock, although it *might* be more costly than using `KeQueryPerformanceCounter()`.  (And if it's *not* more costly, it's probably the best mode on 64-bit Windows, given that RDTSC isn't being used.)

Furthermore, given that there's now a `pcap_set_tstamp_type()` in libpcap, having the time stamp type be per-`pcap_t`, rather than system-wide, might be useful.  You'd offer a choice between:

- `PCAP_TSTAMP_HOST` - this would use `KeQuerySystemTime()` prior to Windows 8 and `KeQuerySystemTimePrecise()` on Windows 8 and later, and would always be available (it's the default in libpcap);
- `PCAP_TSTAMP_HOST_LOWPREC` - this would always use `KeQuerySystemTime()`, and would be always be available;
- `PCAP_TSTAMP_HOST_HIPREC` - this would always use `KeQuerySystemTimePrecise()`, and would only be available on Windows 8 and later.

If the other time stamp types are useful, we could add new `PCAP_TSTAMP_` types for them, and make them available only on Windows (the `PCAP_TSTAMP_ADAPTER` types are available only on Linux - and they have a number of problems, not the least of which is that they give time as seconds since January 1, 1970, 00:00:00 *TAI* with at least some adapters; don't get me started on UN\*X time stamps and leap seconds...).

**Comment by guyharris** [comment]
> So should we have the default time stamp type, if the `HKLM\System\CurrentControlSet\Services\NPF\TimestampMode` registry key is absent, be:
> 
> * `TIMESTAMPMODE_SINGLE_SYNCHRONIZATION` if `KeQuerySystemTimePrecise()` isn't available;
> * `TIMESTAMPMODE_QUERYSYSTEMTIMEPRECISE` if `KeQuerySystemTimePrecise()` isn't available is available?
> 
> That way, if the registry key isn't set, Windows 8 and later will default to a time stamp type that is 1) high resolution and 2) synchronized with the system time.

This would let Wireshark and tcpdump get high-precision times on Windows 8 and later without any source changes.

**Comment by guyharris** [comment]
OK, I've checked in the libpcap changes I used to test the new `PacketGetTimestampModes()` code as the-tcpdump-group/libpcap@b75571b42ea1c6fe43cca05e9a2f0996ebc94991.  Backport those to Npcap's libpcap code and give that a try on Windows 10, using tcpdump.

**Comment by matman13** [comment]
For now, we are having to run npcap in WinPcap-compatibility mode to support our legacy software.  To use the TIMESTAMPMODE_QUERYSYSTEMTIME_PRECISE timestamping mode, I would need to set the HKLM\System\CurrentControlSet\Services\NPF\TimestampMode key or the HKLM\System\CurrentControlSet\Services\npcap\TimestampMode key?  And do I set the value to 2 or 4?

**Comment by fyodor** [comment]
Thanks everyone.  I believe this was implemented a while back and so this issue can be closed.  It's documented in the [Npcap timestamp guide](https://npcap.com/guide/wpcap/pcap-tstamp.html) (which comes from libpcap).  So it's available on a per-handle basis rather than being systemwide like with the old Winpcap registry entries. Some comments from @dmiller-nmap: The default is  HIPREC_UNSYNCED, which uses KeQuerySystemTimePrecise once at the beginning of the capture, then uses KeQueryPerformanceCounter to stamp later packets based on CPU ticks. We call that TIMESTAMPMODE_SINGLE_SYNCHRONIZATION. The TIMESTAMPMODE_QUERYSYSTEMTIME calls KeQuerySystemTime for every packet, and was supported (registry entry for whole system) by WinPcap. Libpcap calls that PCAP_TSTAMP_HOST_LOWPREC. The new mode is TIMESTAMPMODE_QUERYSYSTEMTIME_PRECISE, which libpcap calls PCAP_TSTAMP_HOST_HIPREC, which calls KeQuerySystemTimePrecise for every packet. Both those last 2 do not drift from wall clock time, but may run forwards or backwards according to leap seconds, time zones, system time changes, etc. But the default is a monotonic (always increasing) clock. Both are needed in different situations.
