### ISSUE TITLE
Npcap service does not work

### ISSUE THREAD

**Issue by nxenon** [nmap/npcap#716]
## Wireshark can not load interfaces after windows 11 upgrade

Local interfaces are unavailable because the packet capture driver isn't loaded.
You can fix this by running 
net start npcap
if you have Npcap installed or 
net start npf
if you have WinPcap installed. Both commands must be run as Administrator.

## What is the current bug behavior?
when I run starting service command:

```
C:\Windows\System32>net start npcap
System error 2 has occurred.

The system cannot find the file specified.
```

```
C:\Windows\System32>net start npf
The service name is invalid.

More help is available by typing NET HELPMSG 2185.
```

```
C:\Windows\System32>NET HELPMSG 2185

The service name is invalid.
```

I installed the npcap and wireshark many times.
NpCap Version:1.79
Wireshark Version: 4.2.2

I **just** see loopback interface and when i click on it:
![image](https://github.com/nmap/npcap/assets/61124903/2475b295-45cd-4ab1-bbae-c61fa0149270)

**Comment by gvanem** [comment]
Try to dig into the EventLog with a `psloglist.exe -s | c:\Windows\System32\find.exe "Npcap Packet Driver"` 
for hints. Or for `"NPCAP"`. SysInternal's psloglist program can be downloaded here:
 https://learn.microsoft.com/en-gb/sysinternals/downloads/psloglist

**Comment by nxenon** [comment]
I have found the problem. I just copied npcap.sys from Program Files\npcap.sys to Windows\System32\Drivers\
