### ISSUE TITLE
Error 8007007e while installing npcap

### ISSUE THREAD

**Issue by KonradCzerw** [nmap/npcap#72]
When I try to install Npcap every time i get this error:
![npcap](https://user-images.githubusercontent.com/45497774/49311335-2deb1480-f4e1-11e8-97e1-bacdd639fb73.png)

In the details there was written
`Unknown error! 8007007e`

If i need to upload any files then just ask

**Comment by dmiller-nmap** [comment]
Thanks for this report. I am consolidating all instances of error 8007007e (ERROR_MOD_NOT_FOUND) at #135. Please check that issue for potential workarounds or fixes.

**Comment by Darren-greenhand** [comment]
sorry.but have you solved this problem?
I meet the same problem on my windows 10
by the way I am a really green-hand
