### ISSUE TITLE
Npcap Bug Report

### ISSUE THREAD

**Issue by shikhartandon1993** [nmap/npcap#722]
![MicrosoftTeams-image](https://github.com/nmap/npcap/assets/25962245/e7094c2b-22c4-4337-a9fb-d26bfecf19fe)

**Comment by shikhartandon1993** [comment]
I have tried installing older versions and newer versions  and in admin mode but nothing seems to install npcap

**Comment by shikhartandon1993** [comment]
This is on Windows11

**Comment by gvanem** [comment]
*Module not found*.

**Comment by shikhartandon1993** [comment]
Hi, Can you recommend what should be done here? Wireshark wont work without npcap and npcap is not getting installed even in admin mode

**Comment by fyodor** [comment]
Duplicate of #135
