### ISSUE TITLE
pcap_oid_get_request is missing in npcap-1.79.exe

### ISSUE THREAD

**Issue by joshuafc** [nmap/npcap#728]
I have download sdk from https://npcap.com/#download

https://npcap.com/dist/npcap-1.79.exe
https://npcap.com/dist/npcap-sdk-1.13.zip

There is no pcap_oid_get_request in C:\Windows\system32\wpcap.dll

**Comment by guyharris** [comment]
It's in pcap.c in libpcap 1.10.4, if `_WIN32` is defined; which libpcap source is used to build Npcap?

And what controls which APIs are exported from wpcap.dll?

**Comment by dmiller-nmap** [comment]
@joshuafc Thanks for reporting this. I extracted all 3 architectures of `wpcap.dll` from our installer and verified that `pcap_oid_get_request` is exported using `dumpbin /exports` . I also see it in `wpcap.lib` in the 1.13 SDK. Can you provide some details about what you have tried and how it is not working?

**Comment by joshuafc** [comment]
sorry, wrong dll is loaded, there is an other one in the system.
