### ISSUE TITLE
BSOD during VMware player (network driver) installation

### ISSUE THREAD

**Issue by Alan72104** [nmap/npcap#729]
**Describe the bug**
Consistent BSOD with BUGCODE_NDIS_DRIVER happens during VMware player network driver installation

Could be a copy of #726

**To Reproduce**
1. Install VMware player
2. Wait until it gets to the network driver stage
3. BSOD

**Diagnostic information**
* Windows 11 Home Version 23H2 (OS Build 22631.3527)
* npcap 1.79
* Used Wireshark portable 4.0.4
* Installing VMware-player-17.5.1-23298084
* [install.log](https://github.com/nmap/npcap/files/15279699/install.log)
* [DiagReport-20240510-122623.txt](https://github.com/nmap/npcap/files/15279700/DiagReport-20240510-122623.txt)
* [051024-8375-01.dmp.zip](https://github.com/nmap/npcap/files/15279733/051024-8375-01.zip)

**Stacktrace**
```
nt!KeBugCheckEx
ndis!NdisAllocateCloneOidRequest+0x3d494
npcap!NPF_OidRequest+0x2e [C:\Users\Nmap\Documents\Repos\npcap\packetWin7\npf\npf\Openclos.c @ 2564] 
ndis!ndisFDoOidRequestInternal+0x339
nt!KeExpandKernelStackAndCalloutInternal+0x7a
nt!KeExpandKernelStackAndCalloutEx+0x1d
ndis!ndisQueueOidRequest+0x292
ndis!ndisMOidRequest+0x217
ndis!NdisOidRequest+0x5b
raspppoe!PrSetPacketFilterForAdapter+0xbf
raspppoe!PrBindAdapterEx+0x15c
ndis!ndisInvokeBindAdapter+0x71
ndis!ndisBindNdis6Protocol+0x51a
ndis!ndisBindProtocol+0x8e
ndis!Ndis::BindEngine::Iterate+0x419
ndis!Ndis::BindEngine::UpdateBindings+0xe3
ndis!Ndis::BindEngine::UpdateBindingsWorkItem+0x44
ndis!KWorkItemBase<Ndis::BindEngine,KWorkItem<Ndis::BindEngine> >::CallbackThunk+0x12
nt!ExpWorkerThread+0x155
nt!PspSystemThreadStartup+0x57
nt!KiStartSystemThread+0x34
```

**Comment by dmiller-nmap** [comment]
Duplicate #296
