### ISSUE TITLE
Need instructions for building entire project from A to Z via command line (Cygwin, MSYS, VS)

### ISSUE THREAD

**Issue by eabase** [nmap/npcap#760]
**Describe the bug**
There is no information about the steps needed to build a vanilla project from command line. 

**To Reproduce**
```
# git clone https://github.com/nmap/npcap.git
# cd npcap
# git submodule update --init --recursive --remote # ????
# THEN WHAT?

```

**Expected behavior**
A clear and concise description of how to compile the project!

**Screenshots**
No not me, **You** should post the screenshots in your README! 

**Diagnostic information**
* `Microsoft Windows 11 Pro (64-bit)`

**Additional context**

- Also your BAT scripts are trying to build for both ARM and x86, which are useless for me. (How to turn this off?)
- Why are you still using 30 year old BAT scripts? Please convert them to Powershell.
- What are the exact build requirements (and/or options thereof)?

**Comment by dmiller-nmap** [comment]
To quote from the Npcap license file:

>Even though Npcap source code is publicly available for review, it is
not open source software and may not be redistributed or used in other
software without special permission from the Nmap Project.

There is no need for users to build the entire Npcap project directly. Binary installers and the Npcap SDK are available for download at https://npcap.com/#download

**Comment by eabase** [comment]
> There is no need for users to build the entire Npcap project directly.

It is needed because I'm not building `npcap`, I'm building something else, that requires building `libpcap` library files. But since window is using npcap instead, I have to compile. So IDK why you would say that. Did I miss something?

**Comment by markpizz** [comment]
You DO NOT need to build libpcap to use npcap.  All you need is to look closely at the Npcap SDK.
