### ISSUE TITLE
Npcap 802.11 monitor mode FCS and capture stopping after malformed packet

### ISSUE THREAD

**Issue by thoukydides** [nmap/npcap#90]
I am attempting to use Npcap to capture raw IEEE 802.11 traffic from a Netgear A6200 in monitor mode using Wireshark. However, this fails in two ways (both illustrated in [Capture.zip](https://github.com/nmap/nmap/files/1385526/Capture.zip)):

1. _The captured packets all include an FCS, but the Radiotap Flags field is 0x00 indicating "FCS at end: False"._
This results in Wireshark incorrectly treating the FCS as being part of the payload. For Control frames this results in four undecoded bytes after the MAC header. For Management frames this results in an error (typically either "Malformed Packet" or "Packet size limited during capture") when the FCS is decoded as a Tagged parameter (information element).
This is almost the opposite of nmap/nmap#1028, in which the Flags field has "FCS at end: True" but there is no FCS in the capture.

2. _After a short time (typically a few minutes) the capture stops with a packet that has an invalid Radiotap header._
This usually has a few (typically 1~16) spurious bytes inserted prior to the correct Radiotap header. Occasionally one extra packet is captured after the one with the Radiotap error.
This may be the same as nmap/nmap#1001.

Both the Promiscuous and Monitor Mode options are ticked in the Capture Interfaces window.

I have tried using the "Assume packets have FCS" option, but this appears to be ignored. Based on https://www.wireshark.org/lists/wireshark-dev/201410/msg00079.html that is the intended behaviour, but it is not helpful in this case.
> There are three flavors of 802.11 packet provided to the 802.11 dissector:
> 	1) packets from sources that indicate whether the packet includes the FCS, such as some capture file formats;
> 	2) packets that include metadata that indicates whether the FCS is included, such 802.11+radiotap radiotap packets;
> 	3) packets that don't come from a source that indicates whether the packet includes the FCS.
> 
> The preference works only for packets of type 3), as it's unnecessary for packets of type 1) or 2).

The same behaviour occurs with Npcap installed in both WinPcap API-compatible and non-compatible modes.

These are the software and hardware versions being used:
- Npcap 0.94 (Windows installer)
- Wireshark version 2.4.2 (v2.4.2-0-gb6c63ae086) 64-bit
- Windows 10 Home version 1703 (OS Build 15063.674) 64-bit
- Netgear A6200 v1 Wi-Fi Adapter version 1.0.0.35, driver version 6.32.145.8

Here is the output from DiagReport:
- [DiagReport-20171015-142335.txt](https://github.com/nmap/nmap/files/1385466/DiagReport-20171015-142335.txt)

and here are the installation log files:
- [setupapi.dev.log](https://github.com/nmap/nmap/files/1385465/setupapi.dev.log)
- [install.log](https://github.com/nmap/nmap/files/1385467/install.log)
- [NPFInstall.log](https://github.com/nmap/nmap/files/1385468/NPFInstall.log)

**Comment by dmiller-nmap** [comment]
Merging with #76.
