### ISSUE TITLE
802.11 malformed packets in monitor mode

### ISSUE THREAD

**Issue by natiya** [nmap/npcap#92]
I'm capturing 802.11 packets in monitor mode and all of them are malformed. I attached an example of one of the capture [here](https://www.dropbox.com/s/cv23xw1by25e2v0/WPS_successful_malformed.pcap?dl=0). If you filter by eap or eapol, that should be a sucessful handshaking, but I can't see it because it's all malformed.

I tried two WiFi adapters:

- NetGear AC1200
- Cisco LINKSYS  WUSB100

And I used:

- tshark command line
- dumpcap command line
- Acrylic

I repeated the same process in a Windows Server 2008 with an AirPcap dongle and it works perfectly.

I'm not sure what component is failing: 

- Windows 10
- my adapters
- Wireshark/Npcap on Windows 10

I run the capture from 2 different PCs, both using Windows 10, and same issue happens.

My problem also is that AirPcap is not available for Windows 10.

Any solution?

**Comment by dmiller-nmap** [comment]
Merging with #76.
